# 01 - 各GSEを AnnData 化して中身を確認

GSEごとに「ロード → その場で確認」を行う（旧 01+02 を統合）。生カウントは `adata.X`。ここでは機械的な obs（sample_id, source_file 等）だけ。genotype/treatment/condition は **02 で人間が設定**する。

先に download/extract を済ませること（`./run.sh` または `scripts/01..03`）。GSE295514 は先に R ノートブック `notebooks/R/01_GSE295514_read_rds.ipynb` を実行。

In [3]:
import sys
from pathlib import Path

# config/dataset_manifest.yaml を持つ v2 ルートを探して src を import パスに追加
ROOT = Path.cwd()
while not (ROOT / "config" / "dataset_manifest.yaml").exists() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / "src"))
print("project root:", ROOT)

import manifest_utils as mf
man = mf.load_manifest()
paths = mf.project_paths(ROOT)
mf.ensure_dirs(paths)

import io_10x
import io_dense
import anndata_utils as au
import notebook_report_utils as nb

adatas = {}

project root: /home/suzuki/Learn/SMA/v2

## GSE287569

10x .h5（TAR of H5）

In [2]:
ds = mf.get_dataset(man, "GSE287569")
adata = io_10x.load_10x_h5_per_sample(ds, paths)
adatas["GSE287569"] = adata
nb.summarize_adata(adata, name="GSE287569")
adata

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

=== GSE287569 ===
15854 cells x 32285 genes | X sparse=True dtype=float32 min=0.0 max=11865.0 sum=142210288.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (8): ['gene_ids', 'feature_types', 'genome', 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 15854 × 32285
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_ids', 'feature_types', 'genome', 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [3]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,cell_id
GSE287569_SOD1-s1_AAACCCAGTTATGGTC-1,AAACCCAGTTATGGTC-1,SOD1-s1,SOD1_s1,GSM8748142,GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5,GSE287569,GSE287569_sc_spinalcord_sod1_ripk1i,GSE287569_SOD1-s1_AAACCCAGTTATGGTC-1
GSE287569_SOD1-s1_AAACGAAAGGTAAGTT-1,AAACGAAAGGTAAGTT-1,SOD1-s1,SOD1_s1,GSM8748142,GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5,GSE287569,GSE287569_sc_spinalcord_sod1_ripk1i,GSE287569_SOD1-s1_AAACGAAAGGTAAGTT-1
GSE287569_SOD1-s1_AAACGAATCTCGAGTA-1,AAACGAATCTCGAGTA-1,SOD1-s1,SOD1_s1,GSM8748142,GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5,GSE287569,GSE287569_sc_spinalcord_sod1_ripk1i,GSE287569_SOD1-s1_AAACGAATCTCGAGTA-1
GSE287569_SOD1-s1_AAAGGATCAAGAAATC-1,AAAGGATCAAGAAATC-1,SOD1-s1,SOD1_s1,GSM8748142,GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5,GSE287569,GSE287569_sc_spinalcord_sod1_ripk1i,GSE287569_SOD1-s1_AAAGGATCAAGAAATC-1
GSE287569_SOD1-s1_AAAGGATGTCGAGTTT-1,AAAGGATGTCGAGTTT-1,SOD1-s1,SOD1_s1,GSM8748142,GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5,GSE287569,GSE287569_sc_spinalcord_sod1_ripk1i,GSE287569_SOD1-s1_AAAGGATGTCGAGTTT-1

,gene_ids,feature_types,genome,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
Xkr4,ENSMUSG00000051951,Gene Expression,mm10,Xkr4,XKR4,ENSMUSG00000051951,ENSMUSG00000051951,Gene Expression
Gm1992,ENSMUSG00000089699,Gene Expression,mm10,Gm1992,GM1992,ENSMUSG00000089699,ENSMUSG00000089699,Gene Expression
Gm19938,ENSMUSG00000102331,Gene Expression,mm10,Gm19938,GM19938,ENSMUSG00000102331,ENSMUSG00000102331,Gene Expression
Gm37381,ENSMUSG00000102343,Gene Expression,mm10,Gm37381,GM37381,ENSMUSG00000102343,ENSMUSG00000102343,Gene Expression
Rp1,ENSMUSG00000025900,Gene Expression,mm10,Rp1,RP1,ENSMUSG00000025900,ENSMUSG00000025900,Gene Expression

--- cell_id_original (15828 unique) ---
cell_id_original
CAGGGCTAGTGGCGAT-1    2
GTCTGTCGTACCGGAA-1    2
CACCGTTCAACGGCCT-1    2
TTCCAATCACGAGGAT-1    2
CCACGTTGTTCCTACC-1    2
AAACGAACAACAAAGT-1    2
GTTGTCCCAGAAACCG-1    2
AGCTACAGTCTTGCTC-1    2
TACAGGTAGCGCCTAC-1    2
TCGGGACCAAGACTGG-1    2
TGACTCCAGGGCATGT-1    2
AACAACCAGGTTTACC-1    2
TCTATACCAGTAGATA-1    2
GAAACCTAGGCAGCTA-1    2
GGTTCTCGTAGACGGT-1    2
TTTCACATCGTTATCT-1    2
GGTAGAGTCTCGTCAC-1    2
ACTTTCACAGCAGTGA-1    2
ATCGGATTCGGACGTC-1    2
CCGCAAGGTTGTGTAC-1    2
TCCGTGTGTTCTGACA-1    2
GGGAGTACACGACAAG-1    2
TCATTCATCAGCTGAT-1    2
TCGGTCTGTCTGATAC-1    2
CTCCTTTCACGTATAC-1    2
TTGTTGTGTGTGTGGA-1    2
GAATAGACATATGGCT-1    1
GAAGCGACAGCAGTTT-1    1
GAAGCCCTCGAGATAA-1    1
GAAGCCCAGTCTGGAG-1    1

--- sample_id (12 unique) ---
sample_id
SOD1-s11    2326
SOD1-s4     2201
SOD1-s6     2001
SOD1-s7     1913
SOD1-s1     1796
SOD1-s10    1435
SOD1-s12    1019
SOD1-s9      956
SOD1-s3      764
SOD1-s5      608
SOD1-s8      581
SOD1-s2      254

--- sample_label (12 unique) ---
sample_label
SOD1_s11    2326
SOD1_s4     2201
SOD1_s6     2001
SOD1_s7     1913
SOD1_s1     1796
SOD1_s10    1435
SOD1_s12    1019
SOD1_s9      956
SOD1_s3      764
SOD1_s5      608
SOD1_s8      581
SOD1_s2      254

--- gsm_id (12 unique) ---
gsm_id
GSM8748152    2326
GSM8748145    2201
GSM8748147    2001
GSM8748148    1913
GSM8748142    1796
GSM8748151    1435
GSM8748153    1019
GSM8748150     956
GSM8748144     764
GSM8748146     608
GSM8748149     581
GSM8748143     254

--- source_file (12 unique) ---
source_file
GSM8748152_SOD1_s11_filtered_feature_bc_matrix.h5    2326
GSM8748145_SOD1_s4_filtered_feature_bc_matrix.h5     2201
GSM8748147_SOD1_s6_filtered_feature_bc_matrix.h5     2001
GSM8748148_SOD1_s7_filtered_feature_bc_matrix.h5     1913
GSM8748142_SOD1_s1_filtered_feature_bc_matrix.h5     1796
GSM8748151_SOD1_s10_filtered_feature_bc_matrix.h5    1435
GSM8748153_SOD1_s12_filtered_feature_bc_matrix.h5    1019
GSM8748150_SOD1_s9_filtered_feature_bc_matrix.h5      956
GSM8748144_SOD1_s3_filtered_feature_bc_matrix.h5      764
GSM8748146_SOD1_s5_filtered_feature_bc_matrix.h5      608
GSM8748149_SOD1_s8_filtered_feature_bc_matrix.h5      581
GSM8748143_SOD1_s2_filtered_feature_bc_matrix.h5      254

--- source_accession (1 unique) ---
source_accession
GSE287569    15854

--- dataset_id (1 unique) ---
dataset_id
GSE287569_sc_spinalcord_sod1_ripk1i    15854

--- cell_id (15854 unique) ---
cell_id
GSE287569_SOD1-s12_TTTGACTTCTATTGTC-1    1
GSE287569_SOD1-s1_AAACCCAGTTATGGTC-1     1
GSE287569_SOD1-s1_AAACGAAAGGTAAGTT-1     1
GSE287569_SOD1-s1_AAACGAATCTCGAGTA-1     1
GSE287569_SOD1-s1_AAAGGATCAAGAAATC-1     1
GSE287569_SOD1-s1_AAAGGATGTCGAGTTT-1     1
GSE287569_SOD1-s1_AAAGGGCGTGATTGGG-1     1
GSE287569_SOD1-s1_AAAGGTACAGGCTCTG-1     1
GSE287569_SOD1-s1_AAAGGTACATTGGGAG-1     1
GSE287569_SOD1-s1_AAAGGTAGTATGTGTC-1     1
GSE287569_SOD1-s1_AAAGGTATCCGTGGGT-1     1
GSE287569_SOD1-s1_AAAGTCCAGCCGATCC-1     1
GSE287569_SOD1-s1_AAAGTCCAGTATCCTG-1     1
GSE287569_SOD1-s1_AAAGTCCCACCGTCGA-1     1
GSE287569_SOD1-s12_TTCCTCTCAGGCACAA-1    1
GSE287569_SOD1-s12_TTCCTTCCATGAGATA-1    1
GSE287569_SOD1-s12_TTCGGTCGTGTCTTGA-1    1
GSE287569_SOD1-s12_TTCTAGTCAGGATCTT-1    1
GSE287569_SOD1-s12_TTCTTCCGTGGTACAG-1    1
GSE287569_SOD1-s12_TTGAACGTCCGAGGCT-1    1
GSE287569_SOD1-s12_TTGACCCAGTTCCAGT-1    1
GSE287569_SOD1-s12_TTGACCCCAACATACC-1    1
GSE287569_SOD1-s12_TTCAGGATCACCTCAC-1    1
GSE287569_SOD1-s12_TTCATGTCACGATAGG-1    1
GSE287569_SOD1-s12_TTCCAATCACTGCATA-1    1
GSE287569_SOD1-s12_TTCCGGTCAACTCCCT-1    1
GSE287569_SOD1-s12_TTCCGTGAGTCTTCGA-1    1
GSE287569_SOD1-s12_TTCCGTGCATTGCCGG-1    1
GSE287569_SOD1-s12_TTCCGTGGTACCATAC-1    1
GSE287569_SOD1-s12_TTCCTCTCAATTGGTC-1    1

## GSE173524

結合UMI tsv + 核/サンプルメタ

In [4]:
ds = mf.get_dataset(man, "GSE173524")
adata = io_dense.read_combined_umi_with_metadata(ds, paths)
adatas["GSE173524"] = adata
nb.summarize_adata(adata, name="GSE173524")
adata

=== GSE173524 ===
14662 cells x 31040 genes | X sparse=True dtype=float32 min=0.0 max=13923.0 sum=206486784.0
obs columns (136): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'meta_nCount_RNA', 'meta_nFeature_RNA', 'meta_percent.mt', 'meta_nCount_HTO', 'meta_nFeature_HTO', 'meta_HTO_maxID', 'meta_HTO_secondID', 'meta_HTO_margin', 'meta_HTO_classification', 'meta_HTO_classification.global', 'meta_hash.ID', 'meta_SampleID', 'meta_Batch', 'meta_Sex', 'meta_Genotype', 'meta_Group', 'meta_seurat_clusters', 'meta_singler.fine.cluster', 'meta_singler.fine.cell', 'meta_provisional.microglia.subclusters', 'meta_cell.type.refined', 'meta_astrocyte.subclusters', 'meta_microglia.subclusters', 'meta_oligodendrocyte.subclusters', 'meta_sathyamurthy.mapping.cell.type', 'meta_sathyamurthy.mapping.scores', 'meta_neuron.subtype.refined', 'meta_UMAP_1', 'meta_UMAP_2', 'meta_PC_1', 'meta_PC_2', 'meta_PC_3', 'meta_PC_4', 'meta_PC_5', 'meta_PC_6', 'meta_PC_7', 'meta_PC_8', 'meta_PC_9', 'meta_PC_10', 'meta_PC_11', 'meta_PC_12', 'meta_PC_13', 'meta_PC_14', 'meta_PC_15', 'meta_PC_16', 'meta_PC_17', 'meta_PC_18', 'meta_PC_19', 'meta_PC_20', 'meta_PC_21', 'meta_PC_22', 'meta_PC_23', 'meta_PC_24', 'meta_PC_25', 'meta_PC_26', 'meta_PC_27', 'meta_PC_28', 'meta_PC_29', 'meta_PC_30', 'meta_PC_31', 'meta_PC_32', 'meta_PC_33', 'meta_PC_34', 'meta_PC_35', 'meta_PC_36', 'meta_PC_37', 'meta_PC_38', 'meta_PC_39', 'meta_PC_40', 'meta_PC_41', 'meta_PC_42', 'meta_PC_43', 'meta_PC_44', 'meta_PC_45', 'meta_PC_46', 'meta_PC_47', 'meta_PC_48', 'meta_PC_49', 'meta_PC_50', 'meta_PC_51', 'meta_PC_52', 'meta_PC_53', 'meta_PC_54', 'meta_PC_55', 'meta_PC_56', 'meta_PC_57', 'meta_PC_58', 'meta_PC_59', 'meta_PC_60', 'meta_PC_61', 'meta_PC_62', 'meta_PC_63', 'meta_PC_64', 'meta_PC_65', 'meta_PC_66', 'meta_PC_67', 'meta_PC_68', 'meta_PC_69', 'meta_PC_70', 'meta_PC_71', 'meta_PC_72', 'meta_PC_73', 'meta_PC_74', 'meta_PC_75', 'meta_PC_76', 'meta_PC_77', 'meta_PC_78', 'meta_PC_79', 'meta_PC_80', 'meta_PC_81', 'meta_PC_82', 'meta_PC_83', 'meta_PC_84', 'meta_PC_85', 'meta_PC_86', 'meta_PC_87', 'meta_PC_88', 'meta_PC_89', 'meta_PC_90', 'meta_PC_91', 'meta_PC_92', 'meta_PC_93', 'meta_PC_94', 'meta_PC_95', 'meta_PC_96', 'meta_PC_97', 'meta_PC_98', 'meta_PC_99', 'meta_PC_100']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['sample_metadata::GSE173524_metadata.samples.tsv.gz']

AnnData object with n_obs × n_vars = 14662 × 31040
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'meta_nCount_RNA', 'meta_nFeature_RNA', 'meta_percent.mt', 'meta_nCount_HTO', 'meta_nFeature_HTO', 'meta_HTO_maxID', 'meta_HTO_secondID', 'meta_HTO_margin', 'meta_HTO_classification', 'meta_HTO_classification.global', 'meta_hash.ID', 'meta_SampleID', 'meta_Batch', 'meta_Sex', 'meta_Genotype', 'meta_Group', 'meta_seurat_clusters', 'meta_singler.fine.cluster', 'meta_singler.fine.cell', 'meta_provisional.microglia.subclusters', 'meta_cell.type.refined', 'meta_astrocyte.subclusters', 'meta_microglia.subclusters', 'meta_oligodendrocyte.subclusters', 'meta_sathyamurthy.mapping.cell.type', 'meta_sathyamurthy.mapping.scores', 'meta_neuron.subtype.refined', 'meta_UMAP_1', 'meta_UMAP_2', 'meta_PC_1', 'meta_PC_2', 'meta_PC_3', 'meta_PC_4', 'meta_PC_5', 'meta_PC_6', 'meta_PC_7', 'meta_PC_8', 'meta_PC_9', 'meta_PC_10', 'meta_PC_11', 'meta_PC_12', 'meta_PC_13', 'meta_PC_14', 'meta_PC_15', 'meta_PC_16', 'meta_PC_17', 'meta_PC_18', 'meta_PC_19', 'meta_PC_20', 'meta_PC_21', 'meta_PC_22', 'meta_PC_23', 'meta_PC_24', 'meta_PC_25', 'meta_PC_26', 'meta_PC_27', 'meta_PC_28', 'meta_PC_29', 'meta_PC_30', 'meta_PC_31', 'meta_PC_32', 'meta_PC_33', 'meta_PC_34', 'meta_PC_35', 'meta_PC_36', 'meta_PC_37', 'meta_PC_38', 'meta_PC_39', 'meta_PC_40', 'meta_PC_41', 'meta_PC_42', 'meta_PC_43', 'meta_PC_44', 'meta_PC_45', 'meta_PC_46', 'meta_PC_47', 'meta_PC_48', 'meta_PC_49', 'meta_PC_50', 'meta_PC_51', 'meta_PC_52', 'meta_PC_53', 'meta_PC_54', 'meta_PC_55', 'meta_PC_56', 'meta_PC_57', 'meta_PC_58', 'meta_PC_59', 'meta_PC_60', 'meta_PC_61', 'meta_PC_62', 'meta_PC_63', 'meta_PC_64', 'meta_PC_65', 'meta_PC_66', 'meta_PC_67', 'meta_PC_68', 'meta_PC_69', 'meta_PC_70', 'meta_PC_71', 'meta_PC_72', 'meta_PC_73', 'meta_PC_74', 'meta_PC_75', 'meta_PC_76', 'meta_PC_77', 'meta_PC_78', 'meta_PC_79', 'meta_PC_80', 'meta_PC_81', 'meta_PC_82', 'meta_PC_83', 'meta_PC_84', 'meta_PC_85', 'meta_PC_86', 'meta_PC_87', 'meta_PC_88', 'meta_PC_89', 'meta_PC_90', 'meta_PC_91', 'meta_PC_92', 'meta_PC_93', 'meta_PC_94', 'meta_PC_95', 'meta_PC_96', 'meta_PC_97', 'meta_PC_98', 'meta_PC_99', 'meta_PC_100'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'sample_metadata::GSE173524_metadata.samples.tsv.gz'

In [5]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,meta_nCount_RNA,meta_nFeature_RNA,meta_percent.mt,...,meta_PC_91,meta_PC_92,meta_PC_93,meta_PC_94,meta_PC_95,meta_PC_96,meta_PC_97,meta_PC_98,meta_PC_99,meta_PC_100
AAACCCAGTATTGCCA-1_1,AAACCCAGTATTGCCA-1_1,unknown,unknown,unknown,GSE173524_umi.tsv.gz,GSE173524,GSE173524_sn_lumbar_spinalcord_sod1,10077,3204,0.148633,...,-0.106651,-1.143721,1.566262,0.380968,-4.599978,-0.357757,-0.325392,-2.890268,3.364703,-0.249378
AAACCCATCTATTGTC-1_1,AAACCCATCTATTGTC-1_1,unknown,unknown,unknown,GSE173524_umi.tsv.gz,GSE173524,GSE173524_sn_lumbar_spinalcord_sod1,2032,1225,1.407084,...,1.456279,0.263485,-2.528359,-2.961552,0.753655,-1.206445,-1.356943,-1.232553,0.775765,-3.341253
AAACGAAAGGGAGGGT-1_1,AAACGAAAGGGAGGGT-1_1,unknown,unknown,unknown,GSE173524_umi.tsv.gz,GSE173524,GSE173524_sn_lumbar_spinalcord_sod1,9199,3832,6.151806,...,4.890234,1.750166,-1.937150,0.848538,3.675630,-5.614783,0.504687,0.694882,3.672614,2.078597
AAACGAAGTGTCATTG-1_1,AAACGAAGTGTCATTG-1_1,unknown,unknown,unknown,GSE173524_umi.tsv.gz,GSE173524,GSE173524_sn_lumbar_spinalcord_sod1,2411,1339,0.495254,...,-0.738981,0.283068,2.543946,1.355950,-0.088294,2.998298,-0.103778,-1.697340,-1.386300,-1.199633
AAACGCTCACAACGAG-1_1,AAACGCTCACAACGAG-1_1,unknown,unknown,unknown,GSE173524_umi.tsv.gz,GSE173524,GSE173524_sn_lumbar_spinalcord_sod1,6675,2514,0.373134,...,-1.409311,1.078009,2.672169,0.956957,0.060220,1.726419,-3.178649,0.586020,1.225459,1.466314

        gene_symbol gene_symbol_upper  gene_id ensembl_id feature_type
Xkr4           Xkr4              XKR4     Xkr4    unknown      unknown
Gm1992       Gm1992            GM1992   Gm1992    unknown      unknown
Gm37381     Gm37381           GM37381  Gm37381    unknown      unknown
Rp1             Rp1               RP1      Rp1    unknown      unknown
Sox17         Sox17             SOX17    Sox17    unknown      unknown

--- cell_id_original (14662 unique) ---
cell_id_original
TTTGTTGCATTCACAG-1_3    1
AAACCCAGTATTGCCA-1_1    1
AAACCCATCTATTGTC-1_1    1
AAACGAAAGGGAGGGT-1_1    1
AAACGAAGTGTCATTG-1_1    1
AAACGCTCACAACGAG-1_1    1
TTTCAGTGTTTGGAGG-1_3    1
TTTCAGTTCAACCTTT-1_3    1
TTTCAGTTCGAGAGAC-1_3    1
TTTCATGGTTGCCTAA-1_3    1
TTTCATGGTTTACCTT-1_3    1
TTTCATGTCAGAATAG-1_3    1
TTTCATGTCATCCTAT-1_3    1
TTTCATGTCTATCGCC-1_3    1
TTTCACAAGATTAGCA-1_3    1
TTTCACACAATTTCTC-1_3    1
TTTCACACATCCGTGG-1_3    1
TTTCAGTAGGACAGCT-1_3    1
TTTCAGTAGGCCCAAA-1_3    1
TTTCAGTAGTAAACGT-1_3    1
TTTCAGTGTCTTCAAG-1_3    1
TTTCAGTGTGCCTGAC-1_3    1
TTTAGTCCAGCATGCC-1_3    1
TTTAGTCCAGCCCAGT-1_3    1
TTTAGTCCATACAGAA-1_3    1
TTTAGTCGTTACGATC-1_3    1
TTTATGCCAACTCCAA-1_3    1
TTTATGCCAATCCTAG-1_3    1
TTTATGCGTTCCAGGC-1_3    1
TTTATGCTCGAGATAA-1_3    1

--- sample_id (1 unique) ---
sample_id
unknown    14662

--- sample_label (1 unique) ---
sample_label
unknown    14662

--- gsm_id (1 unique) ---
gsm_id
unknown    14662

--- source_file (1 unique) ---
source_file
GSE173524_umi.tsv.gz    14662

--- source_accession (1 unique) ---
source_accession
GSE173524    14662

--- dataset_id (1 unique) ---
dataset_id
GSE173524_sn_lumbar_spinalcord_sod1    14662

--- meta_nFeature_HTO (1 unique) ---
meta_nFeature_HTO
4    14662

--- meta_HTO_maxID (4 unique) ---
meta_HTO_maxID
Hashtag1    4838
Hashtag3    4003
Hashtag2    3781
Hashtag4    2040

--- meta_HTO_secondID (4 unique) ---
meta_HTO_secondID
Hashtag4    8585
Hashtag2    3113
Hashtag3    1710
Hashtag1    1254

--- meta_HTO_classification (4 unique) ---
meta_HTO_classification
Hashtag1    4838
Hashtag3    4003
Hashtag2    3781
Hashtag4    2040

--- meta_HTO_classification.global (1 unique) ---
meta_HTO_classification.global
Singlet    14662

--- meta_hash.ID (4 unique) ---
meta_hash.ID
Hashtag1    4838
Hashtag3    4003
Hashtag2    3781
Hashtag4    2040

--- meta_SampleID (12 unique) ---
meta_SampleID
F1554    2259
F1552    1683
F1319    1554
F1553    1420
F1556    1413
F1555    1409
F1318    1036
F1561     952
F1563     896
F1559     857
F1560     635
F1558     548

--- meta_Batch (3 unique) ---
meta_Batch
B    6079
A    4687
C    3896

--- meta_Sex (2 unique) ---
meta_Sex
M    8619
F    6043

--- meta_Genotype (2 unique) ---
meta_Genotype
WT          8841
SOD1G93A    5821

--- meta_Group (4 unique) ---
meta_Group
WT.M          4838
WT.F          4003
SOD1G93A.M    3781
SOD1G93A.F    2040

--- meta_singler.fine.cluster (13 unique) ---
meta_singler.fine.cluster
Neurons activated        4464
Neurons                  3770
Oligodendrocytes         2250
Astrocytes                915
qNSCs                     762
aNSCs                     615
Endothelial cells         493
NPCs                      452
Monocytes                 374
Erythrocytes              364
Ependymal                  96
Granulocytes               64
Fibroblasts activated      43

--- meta_singler.fine.cell (27 unique) ---
meta_singler.fine.cell
Granulocytes             6214
Neurons activated        1896
Dendritic cells          1646
Erythrocytes              854
Astrocytes                766
Oligodendrocytes          711
Monocytes                 531
Endothelial cells         457
Neurons                   457
qNSCs                     297
Microglia                 181
T cells                   155
aNSCs                      99
NK cells                   92
Astrocytes activated       84
Ependymal                  48
Hepatocytes                43
B cells                    34
Fibroblasts activated      33
Microglia activated        22
Macrophages                17
NPCs                       12
nan                         7
Macrophages activated       2
Fibroblasts senescent       1
OPCs                        1
Cardiomyocytes              1
Fibroblasts                 1

--- meta_provisional.microglia.subclusters (7 unique) ---
meta_provisional.microglia.subclusters
nan    13746
0.0      200
1.0      171
2.0      157
3.0      136
4.0       98
5.0       80
6.0       74

--- meta_cell.type.refined (10 unique) ---
meta_cell.type.refined
Neuron               8800
Oligodendrocyte      2165
Astrocyte            1555
Schwann_Meningeal    1031
Endothelial           501
Microglia             223
OPC                   181
Ependymal              93
Motor_Neuron           67
Fibroblast             46

--- meta_astrocyte.subclusters (5 unique) ---
meta_astrocyte.subclusters
nan    13107
0.0      524
1.0      438
2.0      220
3.0      195
4.0      178

--- meta_microglia.subclusters (3 unique) ---
meta_microglia.subclusters
nan    14439
0.0      132
1.0       76
2.0       15

--- meta_oligodendrocyte.subclusters (5 unique) ---
meta_oligodendrocyte.subclusters
nan    12497
0.0      711
1.0      693
2.0      576
3.0      132
4.0       53

--- meta_sathyamurthy.mapping.cell.type (50 unique) ---
meta_sathyamurthy.mapping.cell.type
Oligos           2056
neurons          1942
astrocytes       1518
VE_4             1115
endo_vascular     505
VI_5              497
unlabeled         385
DE_5              383
DE_11             349
MI_3              296
VE_1              248
DE_14             236
DE_2              231
DE_13             225
VC_2              222
DI_6              220
DE_15             219
DI_1              209
ME_1              208
DE12              204
DE_9              204
DI_8              197
DI_7              193
VC_1              192
DE_7              179
DE_1              161
DI_4              159
DI_3              156
DE_10             155
DI_2              155

--- meta_neuron.subtype.refined (9 unique) ---
meta_neuron.subtype.refined
nan               5889
DE                3089
DI                1589
VE                1317
Neuron_unclear    1016
MI                 542
VI                 496
VC                 350
ME                 198
VM                 176

## GSE167198

Drop-seq dense テキスト（TAR of TXT）

In [6]:
ds = mf.get_dataset(man, "GSE167198")
adata = io_dense.load_dense_or_text_matrix_bundle(ds, paths)
adatas["GSE167198"] = adata
nb.summarize_adata(adata, name="GSE167198")
adata

=== GSE167198 ===
21919 cells x 19777 genes | X sparse=True dtype=float32 min=0.0 max=1769.0 sum=9888544.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['orientation_report::GSM5098907_Sample2_matrix.txt.gz', 'orientation_report::GSM5098908_Sample6_matrix.txt.gz', 'orientation_report::GSM5098909_Sample1_matrix.txt.gz', 'orientation_report::GSM5098910_Sample5_matrix.txt.gz', 'orientation_report::GSM5098911_Sample3_matrix.txt.gz', 'orientation_report::GSM5098912_Sample7_matrix.txt.gz']

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 21919 × 19777
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'orientation_report::GSM5098907_Sample2_matrix.txt.gz', 'orientation_report::GSM5098908_Sample6_matrix.txt.gz', 'orientation_report::GSM5098909_Sample1_matrix.txt.gz', 'orientation_report::GSM5098910_Sample5_matrix.txt.gz', 'orientation_report::GSM5098911_Sample3_matrix.txt.gz', 'orientation_report::GSM5098912_Sample7_matrix.txt.gz'

In [7]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,cell_id
GSE167198_Sample2-matrix-txt-gz_GCACATCCGCCG,GCACATCCGCCG,Sample2-matrix-txt-gz,Sample2_matrix.txt.gz,GSM5098907,GSM5098907_Sample2_matrix.txt.gz,GSE167198,GSE167198_sc_spinalcord_sod1_dropseq,GSE167198_Sample2-matrix-txt-gz_GCACATCCGCCG
GSE167198_Sample2-matrix-txt-gz_CCCGAAAAGTAT,CCCGAAAAGTAT,Sample2-matrix-txt-gz,Sample2_matrix.txt.gz,GSM5098907,GSM5098907_Sample2_matrix.txt.gz,GSE167198,GSE167198_sc_spinalcord_sod1_dropseq,GSE167198_Sample2-matrix-txt-gz_CCCGAAAAGTAT
GSE167198_Sample2-matrix-txt-gz_TCATATTAATAA,TCATATTAATAA,Sample2-matrix-txt-gz,Sample2_matrix.txt.gz,GSM5098907,GSM5098907_Sample2_matrix.txt.gz,GSE167198,GSE167198_sc_spinalcord_sod1_dropseq,GSE167198_Sample2-matrix-txt-gz_TCATATTAATAA
GSE167198_Sample2-matrix-txt-gz_TCGGACAAAGGC,TCGGACAAAGGC,Sample2-matrix-txt-gz,Sample2_matrix.txt.gz,GSM5098907,GSM5098907_Sample2_matrix.txt.gz,GSE167198,GSE167198_sc_spinalcord_sod1_dropseq,GSE167198_Sample2-matrix-txt-gz_TCGGACAAAGGC
GSE167198_Sample2-matrix-txt-gz_CCATAGGTTACN,CCATAGGTTACN,Sample2-matrix-txt-gz,Sample2_matrix.txt.gz,GSM5098907,GSM5098907_Sample2_matrix.txt.gz,GSE167198,GSE167198_sc_spinalcord_sod1_dropseq,GSE167198_Sample2-matrix-txt-gz_CCATAGGTTACN

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
0610005C13Rik,0610005C13Rik,0610005C13RIK,0610005C13Rik,unknown,unknown
0610007N19Rik,0610007N19Rik,0610007N19RIK,0610007N19Rik,unknown,unknown
0610007P14Rik,0610007P14Rik,0610007P14RIK,0610007P14Rik,unknown,unknown
0610009B14Rik,NaN,NaN,NaN,NaN,NaN
0610009B22Rik,0610009B22Rik,0610009B22RIK,0610009B22Rik,unknown,unknown

--- cell_id_original (21877 unique) ---
cell_id_original
TAATCCTAGCCC    6
GCTGGCGACCTT    6
ACTAACATTATT    6
GTATATATTTTA    5
CGCAAGGGAAAG    4
GCGATGGCTTTT    2
TTGTTAAACCTT    2
CGTCCTTCTCGC    2
CCCCTCAGCCGC    2
TTTCAAACTGAC    2
TGCGACTTACTA    2
GGATCCCGTGCT    2
CGGACGCATCGG    2
AGGTACCTCTCA    2
GCACCCCATGTG    2
CTTTTTATAATA    2
TAGTTCTGAGGT    2
GTGATTAGTCTT    2
TTTACGGACTTG    2
TCGACCCTTATC    2
GCTTCACCAGTC    2
TCCCTTGCGCTA    2
CACCGTGTTCTT    2
CTCACAACTTCN    2
GTTCATATTTGT    2
GCACTACTACCT    1
GCCTTGCCTGTT    1
ACTCTCATCGTG    1
ACGCGACTATGG    1
TTGACAGGTTCG    1

--- sample_id (6 unique) ---
sample_id
Sample5-matrix-txt-gz    3900
Sample1-matrix-txt-gz    3851
Sample6-matrix-txt-gz    3825
Sample3-matrix-txt-gz    3781
Sample2-matrix-txt-gz    3774
Sample7-matrix-txt-gz    2788

--- sample_label (6 unique) ---
sample_label
Sample5_matrix.txt.gz    3900
Sample1_matrix.txt.gz    3851
Sample6_matrix.txt.gz    3825
Sample3_matrix.txt.gz    3781
Sample2_matrix.txt.gz    3774
Sample7_matrix.txt.gz    2788

--- gsm_id (6 unique) ---
gsm_id
GSM5098910    3900
GSM5098909    3851
GSM5098908    3825
GSM5098911    3781
GSM5098907    3774
GSM5098912    2788

--- source_file (6 unique) ---
source_file
GSM5098910_Sample5_matrix.txt.gz    3900
GSM5098909_Sample1_matrix.txt.gz    3851
GSM5098908_Sample6_matrix.txt.gz    3825
GSM5098911_Sample3_matrix.txt.gz    3781
GSM5098907_Sample2_matrix.txt.gz    3774
GSM5098912_Sample7_matrix.txt.gz    2788

--- source_accession (1 unique) ---
source_accession
GSE167198    21919

--- dataset_id (1 unique) ---
dataset_id
GSE167198_sc_spinalcord_sod1_dropseq    21919

--- cell_id (21919 unique) ---
cell_id
GSE167198_Sample7-matrix-txt-gz_GTGTCGTCTGGC    1
GSE167198_Sample2-matrix-txt-gz_GCACATCCGCCG    1
GSE167198_Sample2-matrix-txt-gz_CCCGAAAAGTAT    1
GSE167198_Sample2-matrix-txt-gz_TCATATTAATAA    1
GSE167198_Sample2-matrix-txt-gz_TCGGACAAAGGC    1
GSE167198_Sample2-matrix-txt-gz_CCATAGGTTACN    1
GSE167198_Sample2-matrix-txt-gz_CTGCTCGTTTCC    1
GSE167198_Sample2-matrix-txt-gz_GCGGTAGGACAG    1
GSE167198_Sample2-matrix-txt-gz_CCACCAGTTTCT    1
GSE167198_Sample2-matrix-txt-gz_CCACACGTCCTT    1
GSE167198_Sample2-matrix-txt-gz_TATTCACCAGGN    1
GSE167198_Sample2-matrix-txt-gz_AGTAAGATGCAA    1
GSE167198_Sample2-matrix-txt-gz_CCTCGCCTAGGC    1
GSE167198_Sample2-matrix-txt-gz_CCGGAAAGTGTC    1
GSE167198_Sample2-matrix-txt-gz_TTTGGTCCTTGA    1
GSE167198_Sample2-matrix-txt-gz_TTTCTGGCCTGA    1
GSE167198_Sample2-matrix-txt-gz_CCACGTTCTACC    1
GSE167198_Sample2-matrix-txt-gz_TAACCCGTTACT    1
GSE167198_Sample2-matrix-txt-gz_ATAAACCGCGGG    1
GSE167198_Sample2-matrix-txt-gz_CCCTTCTGACAA    1
GSE167198_Sample2-matrix-txt-gz_CCCCCGTTGAGC    1
GSE167198_Sample2-matrix-txt-gz_ATGCTACACCTC    1
GSE167198_Sample2-matrix-txt-gz_TCACGTCCAGCA    1
GSE167198_Sample2-matrix-txt-gz_CCACCCTCGCCN    1
GSE167198_Sample2-matrix-txt-gz_ACCAGCAGCTGC    1
GSE167198_Sample2-matrix-txt-gz_GCCTTTTCTCAT    1
GSE167198_Sample2-matrix-txt-gz_CTCCTGGATAAG    1
GSE167198_Sample2-matrix-txt-gz_CTTAGAACCGTC    1
GSE167198_Sample2-matrix-txt-gz_GACCTTAACCTN    1
GSE167198_Sample2-matrix-txt-gz_GTTTTATTAAAC    1

## GSE167327

MTX/テキスト（CD45 enriched、別扱い）

In [1]:
from pathlib import Path
import gzip
from scipy.io import mmread

base = Path("/home/suzuki/Learn/SMA/v2/data/extracted/GSE167327")

mtx = base / "GSM5101954_counts.mtx.gz"
rows = base / "GSM5101954_counts.mtx.rownames.txt.gz"
cols = base / "GSM5101954_counts.mtx.colnames.txt.gz"

print("mtx exists:", mtx.exists(), mtx.stat().st_size / 1024 / 1024, "MB")
print("rows exists:", rows.exists(), rows.stat().st_size / 1024, "KB")
print("cols exists:", cols.exists(), cols.stat().st_size / 1024, "KB")

with gzip.open(rows, "rt") as f:
    rownames = [line.strip() for line in f if line.strip()]

with gzip.open(cols, "rt") as f:
    colnames = [line.strip() for line in f if line.strip()]

print("n rownames:", len(rownames))
print("n colnames:", len(colnames))
print("rownames head:", rownames[:5])
print("colnames head:", colnames[:5])

X = mmread(mtx).tocsr()
print("mtx shape:", X.shape)
print("nnz:", X.nnz)
print("sum:", X.sum())

mtx exists: True 4.869723320007324 MB
rows exists: True 85.494140625 KB
cols exists: True 12.1513671875 KB
n rownames: 33666
n colnames: 2125
rownames head: ['0610007P14Rik', '0610009B22Rik', '0610009L18Rik', '0610009O20Rik', '0610010F05Rik']
colnames head: ['hbc02013-AGAGGATA:AAACACGG-TGAGGTCT', 'hbc02013-AGAGGATA:AAACCGCC-GCCACATC', 'hbc02013-AGAGGATA:AAACGTGA-CGTACCTA', 'hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG', 'hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC']
mtx shape: (33666, 2125)
nnz: 1469083
sum: 10281603

In [4]:
# ============================================================
# GSE167327
# MTX + rownames + colnames 形式を直接読む
# matrix: genes x cells
# AnnData: cells x genes
# ============================================================

from pathlib import Path
import gzip

import numpy as np
import pandas as pd
import scipy.sparse as sp
from scipy.io import mmread
import anndata as ad

ds = mf.get_dataset(man, "GSE167327")

# ----------------------------
# 1. file path
# ----------------------------
base = paths["extracted"] / "GSE167327"

mtx_path = base / "GSM5101954_counts.mtx.gz"
row_path = base / "GSM5101954_counts.mtx.rownames.txt.gz"
col_path = base / "GSM5101954_counts.mtx.colnames.txt.gz"

print("base:", base)
print("mtx:", mtx_path, mtx_path.exists())
print("rows:", row_path, row_path.exists())
print("cols:", col_path, col_path.exists())

if not mtx_path.exists():
    raise FileNotFoundError(mtx_path)
if not row_path.exists():
    raise FileNotFoundError(row_path)
if not col_path.exists():
    raise FileNotFoundError(col_path)


# ----------------------------
# 2. rownames / colnames
# ----------------------------
with gzip.open(row_path, "rt") as f:
    gene_names = [line.strip() for line in f if line.strip()]

with gzip.open(col_path, "rt") as f:
    cell_names = [line.strip() for line in f if line.strip()]

gene_names = [str(x) for x in gene_names]
cell_names = [str(x) for x in cell_names]

print("n genes from rownames:", len(gene_names))
print("n cells from colnames:", len(cell_names))
print("gene head:", gene_names[:5])
print("cell head:", cell_names[:5])


# ----------------------------
# 3. Matrix Marketを読む
# ----------------------------
X_gene_cell = mmread(mtx_path).tocsr()

print("raw mtx shape:", X_gene_cell.shape)
print("raw mtx nnz:", X_gene_cell.nnz)
print("raw mtx sum:", float(X_gene_cell.sum()))


# ----------------------------
# 4. shape validation & transpose
# ----------------------------
if X_gene_cell.shape == (len(gene_names), len(cell_names)):
    print("Detected orientation: genes x cells")
    X_cell_gene = X_gene_cell.T.tocsr()
elif X_gene_cell.shape == (len(cell_names), len(gene_names)):
    print("Detected orientation: cells x genes")
    X_cell_gene = X_gene_cell.tocsr()
else:
    raise ValueError(
        "Shape mismatch: "
        f"X={X_gene_cell.shape}, "
        f"genes={len(gene_names)}, cells={len(cell_names)}"
    )

print("AnnData X shape:", X_cell_gene.shape)


# ----------------------------
# 5. obsを作る
# ----------------------------
obs_index = [f"GSE167327_{c}" for c in cell_names]

obs = pd.DataFrame(index=pd.Index(obs_index, name=None))
obs["cell_id_original"] = cell_names
obs["cell_id"] = obs.index.astype(str)

obs["sample_id"] = "GSE167327"
obs["sample_label"] = "GSE167327_CD45_enriched"
obs["gsm_id"] = "GSM5101954"

obs["source_file"] = mtx_path.name
obs["source_accession"] = "GSE167327"
obs["parent_gse"] = "GSE167332"
obs["dataset_id"] = ds.get(
    "dataset_id",
    "GSE167327_sc_spinalcord_optn_cd45_enriched_indrop"
)

# 後段で共通化するための最低限metadata
obs["species"] = "Mus musculus"
obs["disease_area"] = "ALS_related_or_neuroinflammation"
obs["tissue"] = "spinal cord"
obs["region"] = "spinal cord"
obs["assay"] = "scRNA-seq"
obs["technology"] = "inDrop"
obs["enrichment"] = "CD45 enriched"
obs["disease_model"] = "Optn floxed/KO"
obs["data_status"] = "raw_or_filtered_count"
obs["processing_status"] = "GEO_supplementary_MTX"

# まだcondition/genotypeはGSM/論文側と照合して手動で入れる
obs["condition_original"] = "unknown"
obs["disease_status"] = "unknown"
obs["genotype"] = "unknown"
obs["treatment"] = "none_or_unknown"
obs["age"] = "unknown"
obs["age_month"] = "unknown"
obs["sex"] = "unknown"
obs["replicate"] = "unknown"


# ----------------------------
# 6. varを作る
# ----------------------------
var = pd.DataFrame(index=pd.Index(gene_names, name=None))
var["gene_symbol"] = var.index.astype(str)
var["gene_symbol_upper"] = var["gene_symbol"].str.upper()
var["gene_id"] = var["gene_symbol"]
var["ensembl_id"] = "unknown"
var["feature_type"] = "Gene Expression"


# ----------------------------
# 7. AnnData作成
# ----------------------------
adata = ad.AnnData(
    X=X_cell_gene.astype(np.float32),
    obs=obs,
    var=var,
)

adata.obs_names_make_unique()
adata.var_names_make_unique()

adata.uns["source_accession"] = "GSE167327"
adata.uns["parent_gse"] = "GSE167332"
adata.uns["dataset_id"] = obs["dataset_id"].iloc[0]
adata.uns["data_status"] = "raw_or_filtered_count"
adata.uns["note"] = (
    "GSE167327 CD45-enriched inDrop data. "
    "Loaded from GSM5101954_counts.mtx.gz with rownames/colnames files. "
    "Original MTX is genes x cells; transposed to cells x genes for AnnData."
)

adatas["GSE167327"] = adata


# ----------------------------
# 8. 確認
# ----------------------------
nb.summarize_adata(adata, name="GSE167327")
display(adata)

display(adata.obs.head())
display(adata.var.head())

_ = nb.show_obs_value_counts(adata, max_unique=30)

print("shape:", adata.shape)
print("X type:", type(adata.X))
print("X dtype:", adata.X.dtype)
print("X nnz:", adata.X.nnz if sp.issparse(adata.X) else np.count_nonzero(adata.X))
print("X sum:", float(adata.X.sum()))

base: /home/suzuki/Learn/SMA/v2/data/extracted/GSE167327
mtx: /home/suzuki/Learn/SMA/v2/data/extracted/GSE167327/GSM5101954_counts.mtx.gz True
rows: /home/suzuki/Learn/SMA/v2/data/extracted/GSE167327/GSM5101954_counts.mtx.rownames.txt.gz True
cols: /home/suzuki/Learn/SMA/v2/data/extracted/GSE167327/GSM5101954_counts.mtx.colnames.txt.gz True
n genes from rownames: 33666
n cells from colnames: 2125
gene head: ['0610007P14Rik', '0610009B22Rik', '0610009L18Rik', '0610009O20Rik', '0610010F05Rik']
cell head: ['hbc02013-AGAGGATA:AAACACGG-TGAGGTCT', 'hbc02013-AGAGGATA:AAACCGCC-GCCACATC', 'hbc02013-AGAGGATA:AAACGTGA-CGTACCTA', 'hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG', 'hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC']
raw mtx shape: (33666, 2125)
raw mtx nnz: 1469083
raw mtx sum: 10281603.0
Detected orientation: genes x cells
AnnData X shape: (2125, 33666)
=== GSE167327 ===
2125 cells x 33666 genes | X sparse=True dtype=float32 min=0.0 max=4714.0 sum=10281603.0
obs columns (27): ['cell_id_original', 'cell_id', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'parent_gse', 'dataset_id', 'species', 'disease_area', 'tissue', 'region', 'assay', 'technology', 'enrichment', 'disease_model', 'data_status', 'processing_status', 'condition_original', 'disease_status', 'genotype', 'treatment', 'age', 'age_month', 'sex', 'replicate']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['source_accession', 'parent_gse', 'dataset_id', 'data_status', 'note']

AnnData object with n_obs × n_vars = 2125 × 33666
    obs: 'cell_id_original', 'cell_id', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'parent_gse', 'dataset_id', 'species', 'disease_area', 'tissue', 'region', 'assay', 'technology', 'enrichment', 'disease_model', 'data_status', 'processing_status', 'condition_original', 'disease_status', 'genotype', 'treatment', 'age', 'age_month', 'sex', 'replicate'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'source_accession', 'parent_gse', 'dataset_id', 'data_status', 'note'

,cell_id_original,cell_id,sample_id,sample_label,gsm_id,source_file,source_accession,parent_gse,dataset_id,species,...,data_status,processing_status,condition_original,disease_status,genotype,treatment,age,age_month,sex,replicate
GSE167327_hbc02013-AGAGGATA:AAACACGG-TGAGGTCT,hbc02013-AGAGGATA:AAACACGG-TGAGGTCT,GSE167327_hbc02013-AGAGGATA:AAACACGG-TGAGGTCT,GSE167327,GSE167327_CD45_enriched,GSM5101954,GSM5101954_counts.mtx.gz,GSE167327,GSE167332,GSE167327_sc_spinalcord_optn_cd45_enriched_indrop,Mus musculus,...,raw_or_filtered_count,GEO_supplementary_MTX,unknown,unknown,unknown,none_or_unknown,unknown,unknown,unknown,unknown
GSE167327_hbc02013-AGAGGATA:AAACCGCC-GCCACATC,hbc02013-AGAGGATA:AAACCGCC-GCCACATC,GSE167327_hbc02013-AGAGGATA:AAACCGCC-GCCACATC,GSE167327,GSE167327_CD45_enriched,GSM5101954,GSM5101954_counts.mtx.gz,GSE167327,GSE167332,GSE167327_sc_spinalcord_optn_cd45_enriched_indrop,Mus musculus,...,raw_or_filtered_count,GEO_supplementary_MTX,unknown,unknown,unknown,none_or_unknown,unknown,unknown,unknown,unknown
GSE167327_hbc02013-AGAGGATA:AAACGTGA-CGTACCTA,hbc02013-AGAGGATA:AAACGTGA-CGTACCTA,GSE167327_hbc02013-AGAGGATA:AAACGTGA-CGTACCTA,GSE167327,GSE167327_CD45_enriched,GSM5101954,GSM5101954_counts.mtx.gz,GSE167327,GSE167332,GSE167327_sc_spinalcord_optn_cd45_enriched_indrop,Mus musculus,...,raw_or_filtered_count,GEO_supplementary_MTX,unknown,unknown,unknown,none_or_unknown,unknown,unknown,unknown,unknown
GSE167327_hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG,hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG,GSE167327_hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG,GSE167327,GSE167327_CD45_enriched,GSM5101954,GSM5101954_counts.mtx.gz,GSE167327,GSE167332,GSE167327_sc_spinalcord_optn_cd45_enriched_indrop,Mus musculus,...,raw_or_filtered_count,GEO_supplementary_MTX,unknown,unknown,unknown,none_or_unknown,unknown,unknown,unknown,unknown
GSE167327_hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC,hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC,GSE167327_hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC,GSE167327,GSE167327_CD45_enriched,GSM5101954,GSM5101954_counts.mtx.gz,GSE167327,GSE167332,GSE167327_sc_spinalcord_optn_cd45_enriched_indrop,Mus musculus,...,raw_or_filtered_count,GEO_supplementary_MTX,unknown,unknown,unknown,none_or_unknown,unknown,unknown,unknown,unknown

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
0610007P14Rik,0610007P14Rik,0610007P14RIK,0610007P14Rik,unknown,Gene Expression
0610009B22Rik,0610009B22Rik,0610009B22RIK,0610009B22Rik,unknown,Gene Expression
0610009L18Rik,0610009L18Rik,0610009L18RIK,0610009L18Rik,unknown,Gene Expression
0610009O20Rik,0610009O20Rik,0610009O20RIK,0610009O20Rik,unknown,Gene Expression
0610010F05Rik,0610010F05Rik,0610010F05RIK,0610010F05Rik,unknown,Gene Expression

--- cell_id_original (2125 unique) ---
cell_id_original
hbc02013-TACTCCTT:TGTTATCA-TTCGGCCT    1
hbc02013-AGAGGATA:AAACACGG-TGAGGTCT    1
hbc02013-AGAGGATA:AAACCGCC-GCCACATC    1
hbc02013-AGAGGATA:AAACGTGA-CGTACCTA    1
hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG    1
hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC    1
hbc02013-AGAGGATA:AAAGAAAG-TAGAAATG    1
hbc02013-AGAGGATA:AAAGAGGC-GTTAACCA    1
hbc02013-AGAGGATA:AAAGCCCG-CTAGATTG    1
hbc02013-AGAGGATA:AAAGCCCG-TAGCTTAT    1
hbc02013-AGAGGATA:AAAGCCCG-TGGTTTCT    1
hbc02013-AGAGGATA:AAAGTCAT-GCAGCATG    1
hbc02013-AGAGGATA:AAATAGCA-AGCAGAAC    1
hbc02013-TACTCCTT:TATCTGTC-GAGGCTGA    1
hbc02013-TACTCCTT:TATCTGTC-TGACCCTC    1
hbc02013-TACTCCTT:TATGTGAA-CCATTACT    1
hbc02013-TACTCCTT:TATGTGAA-TAACCCGT    1
hbc02013-TACTCCTT:TCATACCA-AGCGCGAT    1
hbc02013-TACTCCTT:TCATAGCT-CCAGCAGT    1
hbc02013-TACTCCTT:TCATTTCA-CCGCTGTT    1
hbc02013-TACTCCTT:TCATTTCA-GGGAGGTA    1
hbc02013-TACTCCTT:TAGCCACA-AAATCGTT    1
hbc02013-TACTCCTT:TAGCCACA-CCTATTCA    1
hbc02013-TACTCCTT:TAGCCACA-GGTCTGAC    1
hbc02013-TACTCCTT:TAGTAGCC-GGCCCTTA    1
hbc02013-TACTCCTT:TAGTAGCC-TTTGGGAG    1
hbc02013-TACTCCTT:TAGTCTCT-AGCACCAC    1
hbc02013-TACTCCTT:TATCCACG-GCTCTAGT    1
hbc02013-TACTCCTT:TATCTGTC-AGTGAAAG    1
hbc02013-TACTCCTT:TACGTTCG-CTACTTGT    1

--- cell_id (2125 unique) ---
cell_id
GSE167327_hbc02013-TACTCCTT:TGTTATCA-TTCGGCCT    1
GSE167327_hbc02013-AGAGGATA:AAACACGG-TGAGGTCT    1
GSE167327_hbc02013-AGAGGATA:AAACCGCC-GCCACATC    1
GSE167327_hbc02013-AGAGGATA:AAACGTGA-CGTACCTA    1
GSE167327_hbc02013-AGAGGATA:AAACTGTG-GTCCAAAG    1
GSE167327_hbc02013-AGAGGATA:AAAGAAAG-AACTTAGC    1
GSE167327_hbc02013-AGAGGATA:AAAGAAAG-TAGAAATG    1
GSE167327_hbc02013-AGAGGATA:AAAGAGGC-GTTAACCA    1
GSE167327_hbc02013-AGAGGATA:AAAGCCCG-CTAGATTG    1
GSE167327_hbc02013-AGAGGATA:AAAGCCCG-TAGCTTAT    1
GSE167327_hbc02013-AGAGGATA:AAAGCCCG-TGGTTTCT    1
GSE167327_hbc02013-AGAGGATA:AAAGTCAT-GCAGCATG    1
GSE167327_hbc02013-AGAGGATA:AAATAGCA-AGCAGAAC    1
GSE167327_hbc02013-TACTCCTT:TATCTGTC-GAGGCTGA    1
GSE167327_hbc02013-TACTCCTT:TATCTGTC-TGACCCTC    1
GSE167327_hbc02013-TACTCCTT:TATGTGAA-CCATTACT    1
GSE167327_hbc02013-TACTCCTT:TATGTGAA-TAACCCGT    1
GSE167327_hbc02013-TACTCCTT:TCATACCA-AGCGCGAT    1
GSE167327_hbc02013-TACTCCTT:TCATAGCT-CCAGCAGT    1
GSE167327_hbc02013-TACTCCTT:TCATTTCA-CCGCTGTT    1
GSE167327_hbc02013-TACTCCTT:TCATTTCA-GGGAGGTA    1
GSE167327_hbc02013-TACTCCTT:TAGCCACA-AAATCGTT    1
GSE167327_hbc02013-TACTCCTT:TAGCCACA-CCTATTCA    1
GSE167327_hbc02013-TACTCCTT:TAGCCACA-GGTCTGAC    1
GSE167327_hbc02013-TACTCCTT:TAGTAGCC-GGCCCTTA    1
GSE167327_hbc02013-TACTCCTT:TAGTAGCC-TTTGGGAG    1
GSE167327_hbc02013-TACTCCTT:TAGTCTCT-AGCACCAC    1
GSE167327_hbc02013-TACTCCTT:TATCCACG-GCTCTAGT    1
GSE167327_hbc02013-TACTCCTT:TATCTGTC-AGTGAAAG    1
GSE167327_hbc02013-TACTCCTT:TACGTTCG-CTACTTGT    1

--- sample_id (1 unique) ---
sample_id
GSE167327    2125

--- sample_label (1 unique) ---
sample_label
GSE167327_CD45_enriched    2125

--- gsm_id (1 unique) ---
gsm_id
GSM5101954    2125

--- source_file (1 unique) ---
source_file
GSM5101954_counts.mtx.gz    2125

--- source_accession (1 unique) ---
source_accession
GSE167327    2125

--- parent_gse (1 unique) ---
parent_gse
GSE167332    2125

--- dataset_id (1 unique) ---
dataset_id
GSE167327_sc_spinalcord_optn_cd45_enriched_indrop    2125

--- species (1 unique) ---
species
Mus musculus    2125

--- disease_area (1 unique) ---
disease_area
ALS_related_or_neuroinflammation    2125

--- tissue (1 unique) ---
tissue
spinal cord    2125

--- region (1 unique) ---
region
spinal cord    2125

--- assay (1 unique) ---
assay
scRNA-seq    2125

--- technology (1 unique) ---
technology
inDrop    2125

--- enrichment (1 unique) ---
enrichment
CD45 enriched    2125

--- disease_model (1 unique) ---
disease_model
Optn floxed/KO    2125

--- data_status (1 unique) ---
data_status
raw_or_filtered_count    2125

--- processing_status (1 unique) ---
processing_status
GEO_supplementary_MTX    2125

--- condition_original (1 unique) ---
condition_original
unknown    2125

--- disease_status (1 unique) ---
disease_status
unknown    2125

--- genotype (1 unique) ---
genotype
unknown    2125

--- treatment (1 unique) ---
treatment
none_or_unknown    2125

--- age (1 unique) ---
age
unknown    2125

--- age_month (1 unique) ---
age_month
unknown    2125

--- sex (1 unique) ---
sex
unknown    2125

--- replicate (1 unique) ---
replicate
unknown    2125
shape: (2125, 33666)
X type: <class 'scipy.sparse._csr.csr_matrix'>
X dtype: float32
X nnz: 1469083
X sum: 10281603.0

In [ ]:
# ds = mf.get_dataset(man, "GSE167327")
# adata = io_dense.load_mtx_or_text_bundle(ds, paths)
# adatas["GSE167327"] = adata
# nb.summarize_adata(adata, name="GSE167327")
# adata

=== GSE167327 ===
0 cells x 35789 genes | X sparse=True dtype=float32 min=None max=None sum=None
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['orientation_report::GSM5101954_counts.mtx.colnames.txt.gz', 'orientation_report::GSM5101954_counts.mtx.rownames.txt.gz']

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:872: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    []

    Inferred to be: empty

  names = self._prep_dim_index(names, "obs")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:798: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    []

    Inferred to be: empty

  value_idx = self._prep_dim_index(value.index, attr)
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:872: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    []

    Inferred to be: empty

  names = self._prep_dim_index(names, "obs")
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:798: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    []

    Inferred to be: empty

  value_idx = self._prep_dim_index(value.index, attr)
/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:872: UserWarning:
AnnData expects .obs.index to contain strings, but got values like:
    []

    Inferred to be: empty

  names = self._prep_dim_index(names, "obs")

AnnData object with n_obs × n_vars = 0 × 35789
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'orientation_report::GSM5101954_counts.mtx.colnames.txt.gz', 'orientation_report::GSM5101954_counts.mtx.rownames.txt.gz'

In [ ]:
# # その場で確認
# display(adata.obs.head())
# display(adata.var.head())
# _ = nb.show_obs_value_counts(adata, max_unique=30)

Empty DataFrame
Columns: [cell_id_original, sample_id, sample_label, gsm_id, source_file, source_accession, dataset_id, cell_id]
Index: []

              gene_symbol gene_symbol_upper gene_id ensembl_id feature_type
0610009B22Rik         NaN               NaN     NaN        NaN          NaN
0610009L18Rik         NaN               NaN     NaN        NaN          NaN
0610009O20Rik         NaN               NaN     NaN        NaN          NaN
0610010F05Rik         NaN               NaN     NaN        NaN          NaN
0610010K14Rik         NaN               NaN     NaN        NaN          NaN

--- cell_id_original (0 unique) ---
Series([], )

--- sample_id (0 unique) ---
Series([], )

--- sample_label (0 unique) ---
Series([], )

--- gsm_id (0 unique) ---
Series([], )

--- source_file (0 unique) ---
Series([], )

--- source_accession (0 unique) ---
Series([], )

--- dataset_id (0 unique) ---
Series([], )

--- cell_id (0 unique) ---
Series([], )

## GSE167331

TPM 行列 → processed_TPM

In [11]:
ds = mf.get_dataset(man, "GSE167331")
adata = io_dense.load_dense_gene_by_cell_matrix(ds, paths)
adatas["GSE167331"] = adata
nb.summarize_adata(adata, name="GSE167331")
adata

=== GSE167331 ===
326 cells x 23420 genes | X sparse=True dtype=float32 min=0.0 max=254280.90625 sum=326000000.0
obs columns (7): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['orientation_report::GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz']

AnnData object with n_obs × n_vars = 326 × 23420
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'orientation_report::GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz'

In [12]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id
111617p2_F3_S159,111617p2_F3_S159,GSE167331,GSE167331,unknown,GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz,GSE167331,GSE167331_sc_spinalcord_optn_facs_microglia_sm...
111617p3_E10_S250,111617p3_E10_S250,GSE167331,GSE167331,unknown,GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz,GSE167331,GSE167331_sc_spinalcord_optn_facs_microglia_sm...
111617p1_B3_S15,111617p1_B3_S15,GSE167331,GSE167331,unknown,GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz,GSE167331,GSE167331_sc_spinalcord_optn_facs_microglia_sm...
111617p2_D3_S135,111617p2_D3_S135,GSE167331,GSE167331,unknown,GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz,GSE167331,GSE167331_sc_spinalcord_optn_facs_microglia_sm...
111617p4_H1_S373,111617p4_H1_S373,GSE167331,GSE167331,unknown,GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz,GSE167331,GSE167331_sc_spinalcord_optn_facs_microglia_sm...

        gene_symbol gene_symbol_upper  gene_id ensembl_id feature_type
Itm2a         Itm2a             ITM2A    Itm2a    unknown      unknown
Sergef       Sergef            SERGEF   Sergef    unknown      unknown
Fam109a     Fam109a           FAM109A  Fam109a    unknown      unknown
Dhx9           Dhx9              DHX9     Dhx9    unknown      unknown
Ssu72         Ssu72             SSU72    Ssu72    unknown      unknown

--- cell_id_original (326 unique) ---
cell_id_original
111617p4_G7_S367     1
111617p2_F3_S159     1
111617p3_E10_S250    1
111617p1_B3_S15      1
111617p2_D3_S135     1
111617p4_H1_S373     1
111617p1_H12_S96     1
111617p1_F5_S65      1
111617p2_B2_S110     1
111617p1_F9_S69      1
111617p3_A12_S204    1
111617p3_A11_S203    1
111617p3_H6_S282     1
111617p1_B10_S22     1
111617p1_H2_S86      1
111617p3_F9_S261     1
111617p3_B11_S215    1
111617p3_H12_S288    1
111617p1_E6_S54      1
111617p3_D4_S232     1
111617p4_F8_S356     1
111617p3_F2_S254     1
111617p4_A5_S293     1
111617p3_G7_S271     1
111617p2_B6_S114     1
111617p3_C10_S226    1
111617p2_G6_S174     1
111617p4_E6_S342     1
111617p4_B5_S305     1
111617p2_G7_S175     1

--- sample_id (1 unique) ---
sample_id
GSE167331    326

--- sample_label (1 unique) ---
sample_label
GSE167331    326

--- gsm_id (1 unique) ---
gsm_id
unknown    326

--- source_file (1 unique) ---
source_file
GSE167331_nextseq_180111_rsem.genes.tpm.matrix.gz    326

--- source_accession (1 unique) ---
source_accession
GSE167331    326

--- dataset_id (1 unique) ---
dataset_id
GSE167331_sc_spinalcord_optn_facs_microglia_smartseq2_tpm    326

## GSE219201

10x MTX/サンプル

In [13]:
ds = mf.get_dataset(man, "GSE219201")
adata = io_10x.load_10x_mtx_per_sample(ds, paths)
adatas["GSE219201"] = adata
nb.summarize_adata(adata, name="GSE219201")
adata

=== GSE219201 ===
42758 cells x 32289 genes | X sparse=True dtype=float32 min=0.0 max=5702.0 sum=152031680.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 42758 × 32289
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [14]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,cell_id
GSE219201_WT-1_AAACCTGAGATCTGAA-1,AAACCTGAGATCTGAA-1,WT-1,WT_1,GSM6777767,GSM6777767_WT_1_matrix.mtx.gz,GSE219201,GSE219201_sn_lumbar_spinalcord_sod1_phd1,GSE219201_WT-1_AAACCTGAGATCTGAA-1
GSE219201_WT-1_AAACCTGAGTACGCGA-1,AAACCTGAGTACGCGA-1,WT-1,WT_1,GSM6777767,GSM6777767_WT_1_matrix.mtx.gz,GSE219201,GSE219201_sn_lumbar_spinalcord_sod1_phd1,GSE219201_WT-1_AAACCTGAGTACGCGA-1
GSE219201_WT-1_AAACCTGAGTGGAGTC-1,AAACCTGAGTGGAGTC-1,WT-1,WT_1,GSM6777767,GSM6777767_WT_1_matrix.mtx.gz,GSE219201,GSE219201_sn_lumbar_spinalcord_sod1_phd1,GSE219201_WT-1_AAACCTGAGTGGAGTC-1
GSE219201_WT-1_AAACCTGCAACAACCT-1,AAACCTGCAACAACCT-1,WT-1,WT_1,GSM6777767,GSM6777767_WT_1_matrix.mtx.gz,GSE219201,GSE219201_sn_lumbar_spinalcord_sod1_phd1,GSE219201_WT-1_AAACCTGCAACAACCT-1
GSE219201_WT-1_AAACCTGCAAGAAAGG-1,AAACCTGCAAGAAAGG-1,WT-1,WT_1,GSM6777767,GSM6777767_WT_1_matrix.mtx.gz,GSE219201,GSE219201_sn_lumbar_spinalcord_sod1_phd1,GSE219201_WT-1_AAACCTGCAAGAAAGG-1

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
Xkr4,Xkr4,XKR4,ENSMUSG00000051951,ENSMUSG00000051951,Gene Expression
Gm1992,Gm1992,GM1992,ENSMUSG00000089699,ENSMUSG00000089699,Gene Expression
Gm19938,Gm19938,GM19938,ENSMUSG00000102331,ENSMUSG00000102331,Gene Expression
Gm37381,Gm37381,GM37381,ENSMUSG00000102343,ENSMUSG00000102343,Gene Expression
Rp1,Rp1,RP1,ENSMUSG00000025900,ENSMUSG00000025900,Gene Expression

--- cell_id_original (42606 unique) ---
cell_id_original
GTGCATAAGAGTAAGG-1    2
ATGCGATTCCTCCTAG-1    2
TAGTGGTCACAGACAG-1    2
GGAATAAAGAAGGTTT-1    2
AATAGAGGTTACGATC-1    2
ACATCAGGTTAAGTAG-1    2
CAAGGCCTCAGCTGGC-1    2
AGATTGCTCCTATTCA-1    2
CTACATTTCATTCACT-1    2
GTCATTTTCTCGCGTT-1    2
TACCTTACAGTAACGG-1    2
GTCCCATCAGGTAGTG-1    2
ACGCCAGGTTGACGTT-1    2
AGTAGCTAGACATAGT-1    2
CCACGGATCAGTGCAT-1    2
ACATACGTCACCAGGC-1    2
CCACGGATCTAACCGA-1    2
CACCGTTGTTGGGTTT-1    2
ACAAAGACACTAGTAC-1    2
TTCGGTCCAGTCAGCC-1    2
ACAGCCGTCACTTATC-1    2
CACAAACCATCGATGT-1    2
CTTGGCTTCCCAAGTA-1    2
GTTGAACGTGCCCTTT-1    2
TGAGCATCAAGCCATT-1    2
GATTGGTTCTACGGGC-1    2
AGCGGTCGTGATGTGG-1    2
AGGGTGACAATCGAAA-1    2
CTAAGACTCTGATTCT-1    2
CTGATAGAGGCTACGA-1    2

--- sample_id (6 unique) ---
sample_id
WT-1         9174
WT-2         8028
Phd1-KO-2    7423
Phd1-KO-1    6601
Phd1-KO-3    6145
WT-3         5387

--- sample_label (6 unique) ---
sample_label
WT_1         9174
WT_2         8028
Phd1-KO_2    7423
Phd1-KO_1    6601
Phd1-KO_3    6145
WT_3         5387

--- gsm_id (6 unique) ---
gsm_id
GSM6777767    9174
GSM6777768    8028
GSM6777771    7423
GSM6777770    6601
GSM6777772    6145
GSM6777769    5387

--- source_file (6 unique) ---
source_file
GSM6777767_WT_1_matrix.mtx.gz         9174
GSM6777768_WT_2_matrix.mtx.gz         8028
GSM6777771_Phd1-KO_2_matrix.mtx.gz    7423
GSM6777770_Phd1-KO_1_matrix.mtx.gz    6601
GSM6777772_Phd1-KO_3_matrix.mtx.gz    6145
GSM6777769_WT_3_matrix.mtx.gz         5387

--- source_accession (1 unique) ---
source_accession
GSE219201    42758

--- dataset_id (1 unique) ---
dataset_id
GSE219201_sn_lumbar_spinalcord_sod1_phd1    42758

--- cell_id (42758 unique) ---
cell_id
GSE219201_Phd1-KO-3_TTTGTTGTCACCTTAT-1    1
GSE219201_WT-1_AAACCTGAGATCTGAA-1         1
GSE219201_WT-1_AAACCTGAGTACGCGA-1         1
GSE219201_WT-1_AAACCTGAGTGGAGTC-1         1
GSE219201_WT-1_AAACCTGCAACAACCT-1         1
GSE219201_WT-1_AAACCTGCAAGAAAGG-1         1
GSE219201_Phd1-KO-3_TTTCGATAGGATGAGA-1    1
GSE219201_Phd1-KO-3_TTTCGATCAACCAATC-1    1
GSE219201_Phd1-KO-3_TTTCGATCATGACCCG-1    1
GSE219201_Phd1-KO-3_TTTCGATTCCTACTGC-1    1
GSE219201_Phd1-KO-3_TTTCGATTCGAGAGCA-1    1
GSE219201_Phd1-KO-3_TTTGACTGTCCAAAGG-1    1
GSE219201_Phd1-KO-3_TTTGACTGTTACCCAA-1    1
GSE219201_Phd1-KO-3_TTTGACTTCAAGTGTC-1    1
GSE219201_Phd1-KO-3_TTTCATGGTCGCAGTC-1    1
GSE219201_Phd1-KO-3_TTTCATGGTTGGCCGT-1    1
GSE219201_Phd1-KO-3_TTTCCTCAGGACCCAA-1    1
GSE219201_Phd1-KO-3_TTTCCTCAGTAGGATT-1    1
GSE219201_Phd1-KO-3_TTTCCTCCAAGTCCCG-1    1
GSE219201_Phd1-KO-3_TTTCCTCGTCCTGTTC-1    1
GSE219201_Phd1-KO-3_TTTCCTCTCCGCATAA-1    1
GSE219201_Phd1-KO-3_TTTCCTCTCGCAAGAG-1    1
GSE219201_Phd1-KO-3_TTTCACATCCACGTGG-1    1
GSE219201_Phd1-KO-3_TTTCAGTAGCTACTAC-1    1
GSE219201_Phd1-KO-3_TTTCAGTAGTCCGCGT-1    1
GSE219201_Phd1-KO-3_TTTCAGTGTGTCCGTG-1    1
GSE219201_Phd1-KO-3_TTTCAGTTCCGTGGCA-1    1
GSE219201_Phd1-KO-3_TTTCAGTTCGTCTACC-1    1
GSE219201_Phd1-KO-3_TTTCATGCACCGCTGA-1    1
GSE219201_Phd1-KO-3_TTTCATGCATTGTCGA-1    1

## GSE242939

10x MTX/サンプル（GSE242942 の scRNA SubSeries）

In [15]:
ds = mf.get_dataset(man, "GSE242939")
adata = io_10x.load_10x_mtx_per_sample(ds, paths)
adatas["GSE242939"] = adata
nb.summarize_adata(adata, name="GSE242939")
adata

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

=== GSE242939 ===
1877260 cells x 32285 genes | X sparse=True dtype=float32 min=0.0 max=7558.0 sum=46584136.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

AnnData object with n_obs × n_vars = 1877260 × 32285
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [16]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,cell_id
GSE242939_CON_AAACCCAAGAAACCAT-1,AAACCCAAGAAACCAT-1,CON,CON,GSM7775330,GSM7775330_CON_matrix.mtx.gz,GSE242939,GSE242939_sc_spinalcord_sod1_pf04457845,GSE242939_CON_AAACCCAAGAAACCAT-1
GSE242939_CON_AAACCCAAGAAACCCA-1,AAACCCAAGAAACCCA-1,CON,CON,GSM7775330,GSM7775330_CON_matrix.mtx.gz,GSE242939,GSE242939_sc_spinalcord_sod1_pf04457845,GSE242939_CON_AAACCCAAGAAACCCA-1
GSE242939_CON_AAACCCAAGAAACTCA-1,AAACCCAAGAAACTCA-1,CON,CON,GSM7775330,GSM7775330_CON_matrix.mtx.gz,GSE242939,GSE242939_sc_spinalcord_sod1_pf04457845,GSE242939_CON_AAACCCAAGAAACTCA-1
GSE242939_CON_AAACCCAAGAAAGTCT-1,AAACCCAAGAAAGTCT-1,CON,CON,GSM7775330,GSM7775330_CON_matrix.mtx.gz,GSE242939,GSE242939_sc_spinalcord_sod1_pf04457845,GSE242939_CON_AAACCCAAGAAAGTCT-1
GSE242939_CON_AAACCCAAGAAATGGG-1,AAACCCAAGAAATGGG-1,CON,CON,GSM7775330,GSM7775330_CON_matrix.mtx.gz,GSE242939,GSE242939_sc_spinalcord_sod1_pf04457845,GSE242939_CON_AAACCCAAGAAATGGG-1

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
Xkr4,Xkr4,XKR4,ENSMUSG00000051951,ENSMUSG00000051951,Gene Expression
Gm1992,Gm1992,GM1992,ENSMUSG00000089699,ENSMUSG00000089699,Gene Expression
Gm19938,Gm19938,GM19938,ENSMUSG00000102331,ENSMUSG00000102331,Gene Expression
Gm37381,Gm37381,GM37381,ENSMUSG00000102343,ENSMUSG00000102343,Gene Expression
Rp1,Rp1,RP1,ENSMUSG00000025900,ENSMUSG00000025900,Gene Expression

--- cell_id_original (1635946 unique) ---
cell_id_original
GACCCTTGTGTCGAGA-1    2
GACCCTTGTGTCCACG-1    2
GACCCTTGTGTATACC-1    2
GACCCTTGTGTACAGG-1    2
GACCCTTGTGGTAACG-1    2
GACCCTTGTGGGATTG-1    2
GACCCTTGTGGCTGAA-1    2
GACCCTTGTGGCACTC-1    2
GACCCTTGTGGATTTC-1    2
CACAGATCAGTCCCGA-1    2
GACCCTTGTGCGACAA-1    2
GACCCTTGTGCACGCT-1    2
GACCCTTGTGCAATGG-1    2
GACCCTTGTGCAACAG-1    2
GACCCTTGTGATGAAT-1    2
GACCCTTGTGAGACGT-1    2
GACCCTTGTGAACTCT-1    2
GACCCTTGTCTTGTCC-1    2
GACCCTTGTCTGTCCT-1    2
GACCCTTGTCTCTGCT-1    2
GACCCTTGTGGATGAC-1    2
GACCCTTGTTTCTATC-1    2
GACCCTTGTTTCGTGA-1    2
GACCCTTGTTTCACAG-1    2
GACCCTTGTTTAGTCG-1    2
GACCCTTGTTTACGAC-1    2
GACCCTTGTTGCTAGT-1    2
GACCCTTGTTGCGGCT-1    2
GACCCTTGTTGATCTG-1    2
GACCCTTGTTCTCGTC-1    2

--- sample_id (2 unique) ---
sample_id
PF     1191772
CON     685488

--- sample_label (2 unique) ---
sample_label
PF     1191772
CON     685488

--- gsm_id (2 unique) ---
gsm_id
GSM7775331    1191772
GSM7775330     685488

--- source_file (2 unique) ---
source_file
GSM7775331_PF_matrix.mtx.gz     1191772
GSM7775330_CON_matrix.mtx.gz     685488

--- source_accession (1 unique) ---
source_accession
GSE242939    1877260

--- dataset_id (1 unique) ---
dataset_id
GSE242939_sc_spinalcord_sod1_pf04457845    1877260

--- cell_id (1877260 unique) ---
cell_id
GSE242939_PF_TTTGTTGTCTTTGCAT-1     1
GSE242939_CON_AAACCCAAGAAACCAT-1    1
GSE242939_CON_AAACCCAAGAAACCCA-1    1
GSE242939_CON_AAACCCAAGAAACTCA-1    1
GSE242939_CON_AAACCCAAGAAAGTCT-1    1
GSE242939_CON_AAACCCAAGAAATGGG-1    1
GSE242939_CON_AAACCCAAGAAATTCG-1    1
GSE242939_CON_AAACCCAAGAACCGCA-1    1
GSE242939_CON_AAACCCAAGAACGCGT-1    1
GSE242939_CON_AAACCCAAGAAGAGCA-1    1
GSE242939_CON_AAACCCAAGAAGCGGG-1    1
GSE242939_CON_AAACCCAAGAAGTCAT-1    1
GSE242939_PF_TTTGTTGTCTCTTCGA-1     1
GSE242939_PF_TTTGTTGTCTGAGCAT-1     1
GSE242939_PF_TTTGTTGTCTGAGGCC-1     1
GSE242939_PF_TTTGTTGTCTGATTCC-1     1
GSE242939_PF_TTTGTTGTCTGATTCT-1     1
GSE242939_PF_TTTGTTGTCTGCATGA-1     1
GSE242939_PF_TTTGTTGTCTGCGATA-1     1
GSE242939_PF_TTTGTTGTCTGCGTCT-1     1
GSE242939_PF_TTTGTTGTCTCGGCTT-1     1
GSE242939_PF_TTTGTTGTCTCGTCAC-1     1
GSE242939_PF_TTTGTTGTCTCGTGAA-1     1
GSE242939_PF_TTTGTTGTCTCGTGGG-1     1
GSE242939_PF_TTTGTTGTCTCTCGAC-1     1
GSE242939_PF_TTTGTTGTCTCTCTTC-1     1
GSE242939_PF_TTTGTTGTCTCTGGTC-1     1
GSE242939_PF_TTTGTTGTCTCTTCAA-1     1
GSE242939_PF_TTTGTTGTCTCATTGT-1     1
GSE242939_PF_TTTGTTGTCTCCCAAC-1     1

## GSE206330

SoupX 処理済み + メタCSV（別扱い）

In [2]:
# ============================================================
# GSE206330 修正版 loader: whitespace header + cell-id harmonization
# ============================================================

import gzip
import csv
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.sparse as sp
import anndata as ad

ds = mf.get_dataset(man, "GSE206330")

raw_dir = paths["raw"] / "GSE206330"

count_path = raw_dir / "GSE206330_processed_SoupX_corrected.txt.gz"
meta_path = raw_dir / "GSE206330_processed_SoupX_corrected_metadata.csv.gz"

print("count_path:", count_path, count_path.exists())
print("meta_path :", meta_path, meta_path.exists())


# ----------------------------
# 1. metadataを読む
# ----------------------------
meta = pd.read_csv(meta_path, index_col=0)
meta.index = meta.index.astype(str)

print("metadata shape:", meta.shape)
print("metadata index head:", list(meta.index[:5]))
display(meta.head())


# ----------------------------
# 2. matrixのheaderだけ読む
# ----------------------------
with gzip.open(count_path, "rt") as f:
    header_line = f.readline().strip()

# whitespace区切りだが、cell IDがquoteされているので csv.reader を使う
cell_ids_matrix = next(csv.reader([header_line], delimiter=" ", quotechar='"'))

cell_ids_matrix = pd.Index(cell_ids_matrix.astype(str) if hasattr(cell_ids_matrix, "astype") else [str(x) for x in cell_ids_matrix])

print("n cell ids in matrix header:", len(cell_ids_matrix))
print("matrix cell ids head:", list(cell_ids_matrix[:5]))
print("metadata rows:", meta.shape[0])


# ----------------------------
# 3. matrix cell IDをmetadata IDに合わせる
# ----------------------------
# matrix: AAACCCAAGGGCTTCC.1M_CTRL
# meta  : AAACCCAAGGGCTTCC-1M_CTRL
#
# barcode中の . は基本ない想定で、最後の sample suffix separator を . -> - にする。
# より安全に「最初の .」だけ置換する。

cell_ids_harmonized = pd.Index([x.replace(".", "-", 1) for x in cell_ids_matrix])

print("harmonized cell ids head:", list(cell_ids_harmonized[:5]))

common = cell_ids_harmonized.intersection(meta.index)
print("common cells:", len(common))
print("common / matrix:", len(common), "/", len(cell_ids_harmonized))
print("common / meta  :", len(common), "/", meta.shape[0])

if len(common) == 0:
    raise ValueError("matrix header cell IDs and metadata index do not match after '.' -> '-' harmonization")

if len(common) != len(cell_ids_harmonized) or len(common) != meta.shape[0]:
    print("WARNING: not all cells match. Will subset to common cells.")
else:
    print("All cells matched.")


# ----------------------------
# 4. 大きなmatrixをchunkで読む
# ----------------------------
def load_gse206330_soupx_whitespace_header(
    count_path,
    meta,
    cell_ids_matrix,
    cell_ids_harmonized,
    dataset_id="GSE206330_sc_cortex_sod1_facs_glia_soupx",
    source_accession="GSE206330",
    chunksize=500,
):
    """
    GSE206330_processed_SoupX_corrected.txt.gz:
      line 1: "cell1" "cell2" ...
      line 2+: "gene" value value ...
    を読む。

    入力matrixは genes x cells。
    出力AnnDataは cells x genes。
    """

    # metadataと共通する列だけ残すためのmask
    common = cell_ids_harmonized.intersection(meta.index)
    keep_mask = cell_ids_harmonized.isin(common)

    kept_matrix_ids = cell_ids_matrix[keep_mask]
    kept_harmonized_ids = cell_ids_harmonized[keep_mask]

    print("kept cells:", len(kept_matrix_ids))

    # metadataはmatrix列順に並べる
    obs = meta.loc[kept_harmonized_ids].copy()
    obs.index = kept_harmonized_ids.astype(str)

    X_blocks = []
    gene_names = []

    # header=0で1行目を列名として読み、index_col=0でgene名をindexにする
    # ただしpandasがheader長とdata長の差をどう扱うかが微妙な場合があるので、
    # namesを明示して読む。
    col_names = ["gene_symbol"] + list(cell_ids_matrix)

    reader = pd.read_csv(
        count_path,
        sep=r"\s+",
        engine="python",
        header=0,
        names=col_names,
        index_col=0,
        chunksize=chunksize,
    )

    for i, chunk in enumerate(reader):
        # chunk: genes_chunk x cells
        if i == 0:
            print("first chunk raw shape:", chunk.shape)
            print("first chunk index head:", list(chunk.index[:5]))
            print("first chunk columns head:", list(chunk.columns[:5]))

        # common cellsだけ残す。列名はmatrix側のdot形式。
        chunk = chunk.loc[:, kept_matrix_ids]

        gene_names.extend(chunk.index.astype(str).tolist())

        # float値あり。SoupX correctedなので整数raw countではない。
        arr = chunk.to_numpy(dtype=np.float32, copy=False)

        # AnnDataは cells x genes
        X_blocks.append(sp.csr_matrix(arr.T))

        if (i + 1) % 10 == 0:
            print(f"  chunks={i+1}, genes={len(gene_names)}")

    X = sp.hstack(X_blocks, format="csr")

    # obs整形
    obs["cell_id_original"] = obs.index.astype(str)
    obs["sample_id"] = obs["Sample"].astype(str) if "Sample" in obs.columns else "unknown"
    obs["sample_label"] = obs["sample_id"].astype(str)
    obs["source_file"] = Path(count_path).name
    obs["source_accession"] = source_accession
    obs["dataset_id"] = dataset_id
    obs["data_status"] = "processed_SoupX_corrected"
    obs["processing_status"] = "SoupX_corrected"

    # manifest metadataも入れる
    obs["species"] = "Mus musculus"
    obs["disease_area"] = "ALS"
    obs["tissue"] = "cerebral cortex"
    obs["region"] = "motor cortex-related cortical glia"
    obs["assay"] = "scRNA-seq"
    obs["technology"] = "10x Genomics"
    obs["enrichment"] = "FACS enriched astrocytes/microglia/oligodendrocytes"
    obs["disease_model"] = "SOD1G93A"

    # conditionなど
    if "Condition" in obs.columns:
        obs["condition_original"] = obs["Condition"].astype(str)
        obs["disease_status"] = obs["Condition"].map({
            "CTRL": "control",
            "SOD1": "ALS_model",
            "ALS": "ALS_model",
        }).fillna(obs["Condition"].astype(str))
    else:
        obs["condition_original"] = "unknown"
        obs["disease_status"] = "unknown"

    if "Age" in obs.columns:
        obs["age"] = obs["Age"].astype(str)
        obs["age_month"] = obs["Age"].astype(str).str.extract(r"(\d+)")[0]
    else:
        obs["age"] = "unknown"
        obs["age_month"] = "unknown"

    if "sex" not in obs.columns:
        obs["sex"] = "unknown"

    # obs_namesを一意化
    obs.index = [f"{source_accession}_{x}" for x in obs.index.astype(str)]
    obs["cell_id"] = obs.index.astype(str)

    # var
    var = pd.DataFrame(index=pd.Index(gene_names, name=None).astype(str))
    var["gene_symbol"] = var.index
    var["gene_symbol_upper"] = var["gene_symbol"].str.upper()
    var["gene_id"] = var["gene_symbol"]
    var["ensembl_id"] = "unknown"
    var["feature_type"] = "Gene Expression"

    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.var_names_make_unique()

    adata.uns["source_accession"] = source_accession
    adata.uns["dataset_id"] = dataset_id
    adata.uns["data_status"] = "processed_SoupX_corrected"
    adata.uns["note"] = "GSE206330 SoupX-corrected processed matrix; not raw UMI counts."

    return adata


adata_fixed = load_gse206330_soupx_whitespace_header(
    count_path=count_path,
    meta=meta,
    cell_ids_matrix=cell_ids_matrix,
    cell_ids_harmonized=cell_ids_harmonized,
    dataset_id=ds["dataset_id"],
    source_accession=ds["source_accession"],
    chunksize=500,
)

adata_fixed.var_names = adata_fixed.var_names.astype(str).str.strip('"')
adata_fixed.var["gene_symbol"] = adata_fixed.var["gene_symbol"].astype(str).str.strip('"')
adata_fixed.var["gene_symbol_upper"] = adata_fixed.var["gene_symbol"].str.upper()
adata_fixed.var["gene_id"] = adata_fixed.var["gene_symbol"]
adata_fixed.var_names_make_unique()
adatas["GSE206330"] = adata_fixed

nb.summarize_adata(adata_fixed, name="GSE206330_fixed")
adata_fixed

count_path: /home/suzuki/Learn/SMA/v2/data/raw/GSE206330/GSE206330_processed_SoupX_corrected.txt.gz True
meta_path : /home/suzuki/Learn/SMA/v2/data/raw/GSE206330/GSE206330_processed_SoupX_corrected_metadata.csv.gz True
metadata shape: (21580, 16)
metadata index head: ['AAACCCAAGGGCTTCC-1M_CTRL', 'AAACGAACAAATGAGT-1M_CTRL', 'AAACGAAGTGGATACG-1M_CTRL', 'AAAGAACAGTCTAACC-1M_CTRL', 'AAAGAACGTCGGCTAC-1M_CTRL']

,nCount_RNA,nFeature_RNA,Sample,Condition,Age,percent.mt,percent.rib,nCount_SCT,nFeature_SCT,seurat_clusters,cell_type,nCount_Y,nFeature_Y,nCount_X,nFeature_X,sex
AAACCCAAGGGCTTCC-1M_CTRL,5070.143290,2006,1M_CTRL,CTRL,1M,0.791865,22.035724,5171,2004,1,Microglia,0.983753,1,250.775332,64,Female
AAACGAACAAATGAGT-1M_CTRL,7314.610309,3210,1M_CTRL,CTRL,1M,2.110448,7.036205,6389,3197,17,Endothelial cells/Pericytes,6.957818,3,246.115832,91,Male
AAACGAAGTGGATACG-1M_CTRL,20098.112040,4571,1M_CTRL,CTRL,1M,2.420975,3.244563,6917,2878,10,Oligodendrocytes,0.000000,0,1645.893974,130,Female
AAAGAACAGTCTAACC-1M_CTRL,4071.954742,1735,1M_CTRL,CTRL,1M,2.074069,12.619476,4656,1735,1,Microglia,1.982298,2,179.219607,51,Male
AAAGAACGTCGGCTAC-1M_CTRL,3142.309766,1480,1M_CTRL,CTRL,1M,1.658441,17.068558,4352,1480,1,Microglia,0.000000,0,162.457076,37,Female

n cell ids in matrix header: 21580
matrix cell ids head: ['AAACCCAAGGGCTTCC.1M_CTRL', 'AAACGAACAAATGAGT.1M_CTRL', 'AAACGAAGTGGATACG.1M_CTRL', 'AAAGAACAGTCTAACC.1M_CTRL', 'AAAGAACGTCGGCTAC.1M_CTRL']
metadata rows: 21580
harmonized cell ids head: ['AAACCCAAGGGCTTCC-1M_CTRL', 'AAACGAACAAATGAGT-1M_CTRL', 'AAACGAAGTGGATACG-1M_CTRL', 'AAAGAACAGTCTAACC-1M_CTRL', 'AAAGAACGTCGGCTAC-1M_CTRL']
common cells: 21580
common / matrix: 21580 / 21580
common / meta  : 21580 / 21580
All cells matched.
kept cells: 21580
first chunk raw shape: (500, 21580)
first chunk index head: ['"4933401J01Rik"', '"Gm26206"', '"Xkr4"', '"Gm18956"', '"Gm37180"']
first chunk columns head: ['AAACCCAAGGGCTTCC.1M_CTRL', 'AAACGAACAAATGAGT.1M_CTRL', 'AAACGAAGTGGATACG.1M_CTRL', 'AAAGAACAGTCTAACC.1M_CTRL', 'AAAGAACGTCGGCTAC.1M_CTRL']
  chunks=10, genes=5000
  chunks=20, genes=10000
  chunks=30, genes=15000
  chunks=40, genes=20000
  chunks=50, genes=25000
  chunks=60, genes=30000
  chunks=70, genes=35000
  chunks=80, genes=40000
  chunks=90, genes=45000
=== GSE206330_fixed ===
21580 cells x 46983 genes | X sparse=True dtype=float32 min=0.0 max=8.123919486999512 sum=66855988.0
obs columns (37): ['nCount_RNA', 'nFeature_RNA', 'Sample', 'Condition', 'Age', 'percent.mt', 'percent.rib', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters', 'cell_type', 'nCount_Y', 'nFeature_Y', 'nCount_X', 'nFeature_X', 'sex', 'cell_id_original', 'sample_id', 'sample_label', 'source_file', 'source_accession', 'dataset_id', 'data_status', 'processing_status', 'species', 'disease_area', 'tissue', 'region', 'assay', 'technology', 'enrichment', 'disease_model', 'condition_original', 'disease_status', 'age', 'age_month', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=['source_accession', 'dataset_id', 'data_status', 'note']

AnnData object with n_obs × n_vars = 21580 × 46983
    obs: 'nCount_RNA', 'nFeature_RNA', 'Sample', 'Condition', 'Age', 'percent.mt', 'percent.rib', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters', 'cell_type', 'nCount_Y', 'nFeature_Y', 'nCount_X', 'nFeature_X', 'sex', 'cell_id_original', 'sample_id', 'sample_label', 'source_file', 'source_accession', 'dataset_id', 'data_status', 'processing_status', 'species', 'disease_area', 'tissue', 'region', 'assay', 'technology', 'enrichment', 'disease_model', 'condition_original', 'disease_status', 'age', 'age_month', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'
    uns: 'source_accession', 'dataset_id', 'data_status', 'note'

In [3]:
display(adata_fixed.obs.head())
display(adata_fixed.var.head())

print("shape:", adata_fixed.shape)
print("X type:", type(adata_fixed.X))
print("X dtype:", adata_fixed.X.dtype)
print("X nnz:", adata_fixed.X.nnz)
print("X sum:", float(adata_fixed.X.sum()))

for col in [
    "Sample",
    "Condition",
    "Age",
    "sex",
    "seurat_clusters",
    "cell_type",
    "sample_id",
    "disease_status",
    "data_status",
]:
    if col in adata_fixed.obs.columns:
        print(f"\n--- {col} ---")
        print(adata_fixed.obs[col].value_counts(dropna=False).head(30))

,nCount_RNA,nFeature_RNA,Sample,Condition,Age,percent.mt,percent.rib,nCount_SCT,nFeature_SCT,seurat_clusters,...,region,assay,technology,enrichment,disease_model,condition_original,disease_status,age,age_month,cell_id
GSE206330_AAACCCAAGGGCTTCC-1M_CTRL,5070.143290,2006,1M_CTRL,CTRL,1M,0.791865,22.035724,5171,2004,1,...,motor cortex-related cortical glia,scRNA-seq,10x Genomics,FACS enriched astrocytes/microglia/oligodendro...,SOD1G93A,CTRL,control,1M,1,GSE206330_AAACCCAAGGGCTTCC-1M_CTRL
GSE206330_AAACGAACAAATGAGT-1M_CTRL,7314.610309,3210,1M_CTRL,CTRL,1M,2.110448,7.036205,6389,3197,17,...,motor cortex-related cortical glia,scRNA-seq,10x Genomics,FACS enriched astrocytes/microglia/oligodendro...,SOD1G93A,CTRL,control,1M,1,GSE206330_AAACGAACAAATGAGT-1M_CTRL
GSE206330_AAACGAAGTGGATACG-1M_CTRL,20098.112040,4571,1M_CTRL,CTRL,1M,2.420975,3.244563,6917,2878,10,...,motor cortex-related cortical glia,scRNA-seq,10x Genomics,FACS enriched astrocytes/microglia/oligodendro...,SOD1G93A,CTRL,control,1M,1,GSE206330_AAACGAAGTGGATACG-1M_CTRL
GSE206330_AAAGAACAGTCTAACC-1M_CTRL,4071.954742,1735,1M_CTRL,CTRL,1M,2.074069,12.619476,4656,1735,1,...,motor cortex-related cortical glia,scRNA-seq,10x Genomics,FACS enriched astrocytes/microglia/oligodendro...,SOD1G93A,CTRL,control,1M,1,GSE206330_AAAGAACAGTCTAACC-1M_CTRL
GSE206330_AAAGAACGTCGGCTAC-1M_CTRL,3142.309766,1480,1M_CTRL,CTRL,1M,1.658441,17.068558,4352,1480,1,...,motor cortex-related cortical glia,scRNA-seq,10x Genomics,FACS enriched astrocytes/microglia/oligodendro...,SOD1G93A,CTRL,control,1M,1,GSE206330_AAAGAACGTCGGCTAC-1M_CTRL

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
4933401J01Rik,4933401J01Rik,4933401J01RIK,4933401J01Rik,unknown,Gene Expression
Gm26206,Gm26206,GM26206,Gm26206,unknown,Gene Expression
Xkr4,Xkr4,XKR4,Xkr4,unknown,Gene Expression
Gm18956,Gm18956,GM18956,Gm18956,unknown,Gene Expression
Gm37180,Gm37180,GM37180,Gm37180,unknown,Gene Expression

shape: (21580, 46983)
X type: <class 'scipy.sparse._csr.csr_matrix'>
X dtype: float32
X nnz: 51808882
X sum: 66855988.0

--- Sample ---
Sample
4M_SOD1    4502
3M_SOD1    3327
2M_SOD1    3193
2M_CTRL    3173
3M_CTRL    3110
1M_SOD1    2285
4M_CTRL    1178
1M_CTRL     812
Name: count, dtype: int64

--- Condition ---
Condition
SOD1    13307
CTRL     8273
Name: count, dtype: int64

--- Age ---
Age
3M    6437
2M    6366
4M    5680
1M    3097
Name: count, dtype: int64

--- sex ---
sex
Male      10950
Female    10630
Name: count, dtype: int64

--- seurat_clusters ---
seurat_clusters
0     2942
1     2932
2     2200
3     1905
4     1878
5     1854
6     1840
7     1679
8     1392
9      716
10     552
11     395
12     282
13     255
14     235
15     165
16     152
17     108
18      98
Name: count, dtype: int64

--- cell_type ---
cell_type
Microglia                               8429
Oligodendrocytes                        6180
Astrocytes                              5536
Perivascular macrophages                 434
Pericytes                                395
Endothelial cells                        235
Oligodendrocyte precursors               165
Endothelial cells/Pericytes              108
Committed oligodendrocyte precursors      98
Name: count, dtype: int64

--- sample_id ---
sample_id
4M_SOD1    4502
3M_SOD1    3327
2M_SOD1    3193
2M_CTRL    3173
3M_CTRL    3110
1M_SOD1    2285
4M_CTRL    1178
1M_CTRL     812
Name: count, dtype: int64

--- disease_status ---
disease_status
ALS_model    13307
control       8273
Name: count, dtype: int64

--- data_status ---
data_status
processed_SoupX_corrected    21580
Name: count, dtype: int64

In [ ]:
# ds = mf.get_dataset(man, "GSE206330")
# adata = io_dense.load_processed_count_matrix_with_metadata(ds, paths)
# adatas["GSE206330"] = adata
# nb.summarize_adata(adata, name="GSE206330")
# adata

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

#### test code

In [ ]:
# ============================================================
# GSE206330 読み取り診断 + AnnData 再構築コード
# 前提:
#   import sys, Path, mf, man, paths, io_dense, au, nb は実行済み
#   ds = mf.get_dataset(man, "GSE206330")
# ============================================================

import gzip
import re
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.sparse as sp
import anndata as ad


# ----------------------------
# 0. dataset / path確認
# ----------------------------
ds = mf.get_dataset(man, "GSE206330")

print("dataset keys:", list(ds.keys()) if isinstance(ds, dict) else type(ds))
print("dataset:", ds)

raw_dir = paths["raw"] / "GSE206330"
extracted_dir = paths["extracted"] / "GSE206330"

print("\nraw_dir:", raw_dir, "exists=", raw_dir.exists())
print("extracted_dir:", extracted_dir, "exists=", extracted_dir.exists())

print("\nraw files:")
for p in sorted(raw_dir.glob("*")):
    print(" ", p.name, p.stat().st_size / 1024 / 1024, "MB")

print("\nextracted files:")
if extracted_dir.exists():
    for p in sorted(extracted_dir.glob("**/*")):
        if p.is_file():
            print(" ", p.relative_to(extracted_dir), p.stat().st_size / 1024 / 1024, "MB")


# ----------------------------
# 1. GSE206330の対象ファイルを探す
# ----------------------------
def find_one_file(candidates, patterns):
    """
    candidates: list[Path]
    patterns: list[str]
    """
    hits = []
    for p in candidates:
        name = p.name
        for pat in patterns:
            if pat in name:
                hits.append(p)
                break
    hits = sorted(set(hits))
    if len(hits) == 0:
        raise FileNotFoundError(f"No file found for patterns={patterns}")
    if len(hits) > 1:
        print("Multiple hits:")
        for h in hits:
            print(" ", h)
        print("Using first:", hits[0])
    return hits[0]


all_files = []
if raw_dir.exists():
    all_files += [p for p in raw_dir.glob("*") if p.is_file()]
if extracted_dir.exists():
    all_files += [p for p in extracted_dir.glob("**/*") if p.is_file()]

count_path = find_one_file(
    all_files,
    patterns=["processed_SoupX_corrected.txt.gz", "processed_SoupX_corrected.txt"]
)

meta_path = find_one_file(
    all_files,
    patterns=["processed_SoupX_corrected_metadata.csv.gz", "processed_SoupX_corrected_metadata.csv"]
)

print("\ncount_path:", count_path)
print("meta_path :", meta_path)


# ----------------------------
# 2. 生ファイルの先頭を確認
# ----------------------------
def open_text_auto(path):
    path = Path(path)
    if path.suffix == ".gz":
        return gzip.open(path, "rt")
    return open(path, "rt")


print("\n=== raw count file first 5 lines, repr ===")
with open_text_auto(count_path) as f:
    for i in range(5):
        line = f.readline()
        print(f"[line {i+1}] len={len(line)}")
        print(repr(line[:1000]))
        print()

print("\n=== metadata first 5 lines, repr ===")
with open_text_auto(meta_path) as f:
    for i in range(5):
        line = f.readline()
        print(f"[line {i+1}] len={len(line)}")
        print(repr(line[:1000]))
        print()


# ----------------------------
# 3. 区切り文字を試す
# ----------------------------
def try_read_head(path, sep, header="infer", index_col=None, nrows=5, engine=None, label=""):
    print(f"\n--- try_read_head: {label} sep={repr(sep)} header={header} index_col={index_col} ---")
    try:
        kwargs = dict(sep=sep, header=header, index_col=index_col, nrows=nrows)
        if engine is not None:
            kwargs["engine"] = engine
        df = pd.read_csv(path, **kwargs)
        print("shape:", df.shape)
        print("columns[:10]:", list(df.columns[:10]))
        print("index[:5]:", list(df.index[:5]))
        display(df.iloc[:5, :min(10, df.shape[1])])
        return df
    except Exception as e:
        print("FAILED:", type(e).__name__, e)
        return None


# 典型パターンを全部試す
_ = try_read_head(count_path, sep="\t", header="infer", index_col=0, nrows=5, label="tab + header + index")
_ = try_read_head(count_path, sep=",",  header="infer", index_col=0, nrows=5, label="comma + header + index")
_ = try_read_head(count_path, sep=r"\s+", header="infer", index_col=0, nrows=5, engine="python", label="whitespace + header + index")

_ = try_read_head(count_path, sep=r"\s+", header=None, index_col=0, nrows=5, engine="python", label="whitespace + NO header + index")

meta_head = try_read_head(meta_path, sep=",", header="infer", index_col=0, nrows=5, label="metadata csv")


# ----------------------------
# 4. metadata全体を読む
# ----------------------------
meta = pd.read_csv(meta_path, index_col=0)
print("\n=== metadata full ===")
print("meta shape:", meta.shape)
print("meta index head:", list(meta.index[:5]))
print("meta columns:", list(meta.columns))
display(meta.head())


# ----------------------------
# 5. count matrixの形式を推定
# ----------------------------
# 1行目のtoken数、2行目のtoken数を見て header 有無を推定する
with open_text_auto(count_path) as f:
    line1 = f.readline().rstrip("\n")
    line2 = f.readline().rstrip("\n")

tokens1 = re.split(r"\s+", line1.strip())
tokens2 = re.split(r"\s+", line2.strip())

print("\n=== token diagnostics ===")
print("line1 token count:", len(tokens1))
print("line2 token count:", len(tokens2))
print("line1 first 10 tokens:", tokens1[:10])
print("line2 first 10 tokens:", tokens2[:10])
print("metadata rows:", meta.shape[0])

# 推定:
# - headerあり: 1行目が cell IDs header、2行目以降が gene + counts
# - headerなし: 各行が gene + counts で、列名はmetadataから補う
#
# よくある判定:
#   len(tokens2) - 1 == meta.shape[0] なら、gene + counts 形式
#   len(tokens1) - 1 == meta.shape[0] かつ tokens1[0]が空/遺伝子名っぽくないならheaderありの可能性
#
headerless_gene_by_cell = (len(tokens2) - 1 == meta.shape[0]) or (len(tokens1) - 1 == meta.shape[0])
print("headerless_gene_by_cell candidate:", headerless_gene_by_cell)

if len(tokens1) > 1:
    print("n numeric-like tokens in line1 after first token:",
          sum(pd.to_numeric(pd.Series(tokens1[1:50]), errors="coerce").notna()))


# ----------------------------
# 6. 小さく読み込んでmetadataと列数確認
# ----------------------------
# headerなし想定で読む
small_no_header = pd.read_csv(
    count_path,
    sep=r"\s+",
    engine="python",
    header=None,
    index_col=0,
    nrows=20
)

print("\n=== small_no_header ===")
print("shape:", small_no_header.shape)
print("index head:", list(small_no_header.index[:5]))
display(small_no_header.iloc[:5, :10])

print("small_no_header columns count:", small_no_header.shape[1])
print("metadata rows:", meta.shape[0])

# headerあり想定で読む
try:
    small_header = pd.read_csv(
        count_path,
        sep=r"\s+",
        engine="python",
        header=0,
        index_col=0,
        nrows=20
    )
    print("\n=== small_header ===")
    print("shape:", small_header.shape)
    print("index head:", list(small_header.index[:5]))
    print("columns head:", list(small_header.columns[:5]))
    display(small_header.iloc[:5, :10])
    print("intersection with metadata index:", len(set(small_header.columns) & set(meta.index)))
except Exception as e:
    small_header = None
    print("\nsmall_header FAILED:", type(e).__name__, e)


# ----------------------------
# 7. 読み込み方を決める
# ----------------------------
# 基本は以下：
# - headerなしで、count列数 == metadata行数なら header=None で読む
# - headerありで、columns と metadata.index が合うなら header=0 で読む
#
# この段階では巨大ファイルなので、いきなりdense DataFrame全体を作る前に
# chunkで sparse AnnData を作る関数を使う。

def build_adata_from_headerless_gene_by_cell_whitespace(
    count_path,
    meta,
    dataset_id="GSE206330_sc_cortex_sod1_facs_glia_soupx",
    source_accession="GSE206330",
    chunksize=1000,
):
    """
    count file:
      gene count count count ...
      gene count count count ...
    のような headerなし whitespace区切り matrix を想定。

    metadata rows = cells と仮定して、列順で対応づける。
    出力AnnDataは cells x genes。
    """
    X_blocks = []
    gene_names = []

    reader = pd.read_csv(
        count_path,
        sep=r"\s+",
        engine="python",
        header=None,
        index_col=0,
        chunksize=chunksize,
    )

    for i, chunk in enumerate(reader):
        # chunk: genes_chunk x cells
        if i == 0:
            print("first chunk shape:", chunk.shape)
            print("first chunk index head:", list(chunk.index[:5]))
            print("metadata rows:", meta.shape[0])

            if chunk.shape[1] != meta.shape[0]:
                raise ValueError(
                    f"Column count in matrix does not match metadata rows: "
                    f"chunk.shape[1]={chunk.shape[1]}, meta.shape[0]={meta.shape[0]}"
                )

        gene_names.extend(chunk.index.astype(str).tolist())

        # 数値化。失敗したらNaNになるので0埋め。
        chunk = chunk.apply(pd.to_numeric, errors="coerce").fillna(0)

        # AnnDataは cells x genes なので transpose
        X_blocks.append(sp.csr_matrix(chunk.T.values.astype(np.float32)))

        if (i + 1) % 10 == 0:
            print(f"  read chunks: {i+1}, genes so far: {len(gene_names)}")

    X = sp.hstack(X_blocks, format="csr")

    obs = meta.copy()
    obs.index = obs.index.astype(str)
    obs["cell_id_original"] = obs.index
    obs["sample_id"] = obs.get("Sample", obs.get("sample", "unknown"))
    obs["sample_label"] = obs["sample_id"].astype(str)
    obs["gsm_id"] = "unknown"
    obs["source_file"] = Path(count_path).name
    obs["source_accession"] = source_accession
    obs["dataset_id"] = dataset_id
    obs["data_status"] = "processed_SoupX_corrected"
    obs["processing_status"] = "SoupX_corrected"

    # meta列が上書きで衝突しないように、元metadata列をmeta_ prefixにも保持したい場合
    # ここでは既存列はそのまま残す。必要なら後段でrename。

    var = pd.DataFrame(index=pd.Index(gene_names, name=None).astype(str))
    var["gene_symbol"] = var.index
    var["gene_symbol_upper"] = var["gene_symbol"].str.upper()
    var["gene_id"] = var["gene_symbol"]
    var["ensembl_id"] = "unknown"
    var["feature_type"] = "unknown"

    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.obs_names = [
        f"{source_accession}_{x}" for x in adata.obs_names.astype(str)
    ]
    adata.obs["cell_id"] = adata.obs_names
    adata.var_names_make_unique()

    return adata


def build_adata_from_header_gene_by_cell_whitespace(
    count_path,
    meta,
    dataset_id="GSE206330_sc_cortex_sod1_facs_glia_soupx",
    source_accession="GSE206330",
    chunksize=1000,
):
    """
    count file:
      gene_or_blank cell1 cell2 cell3 ...
      gene count count count ...
    のような headerあり whitespace区切り matrix を想定。
    """
    # headerだけ読む
    header_df = pd.read_csv(
        count_path,
        sep=r"\s+",
        engine="python",
        header=0,
        index_col=0,
        nrows=1,
    )
    count_columns = header_df.columns.astype(str)

    common = pd.Index(count_columns).intersection(meta.index.astype(str))
    print("header columns:", len(count_columns))
    print("metadata rows:", meta.shape[0])
    print("intersection count:", len(common))

    X_blocks = []
    gene_names = []

    reader = pd.read_csv(
        count_path,
        sep=r"\s+",
        engine="python",
        header=0,
        index_col=0,
        chunksize=chunksize,
    )

    for i, chunk in enumerate(reader):
        if i == 0:
            print("first chunk shape:", chunk.shape)
            print("first chunk index head:", list(chunk.index[:5]))

        # metadataと共通するcellだけにする
        if len(common) > 0:
            chunk = chunk.loc[:, common]

        gene_names.extend(chunk.index.astype(str).tolist())
        chunk = chunk.apply(pd.to_numeric, errors="coerce").fillna(0)
        X_blocks.append(sp.csr_matrix(chunk.T.values.astype(np.float32)))

        if (i + 1) % 10 == 0:
            print(f"  read chunks: {i+1}, genes so far: {len(gene_names)}")

    X = sp.hstack(X_blocks, format="csr")

    if len(common) > 0:
        obs = meta.loc[common].copy()
    else:
        # headerありだがmetadataと合わない場合は列名をobsにする
        obs = pd.DataFrame(index=count_columns)

    obs.index = obs.index.astype(str)
    obs["cell_id_original"] = obs.index
    obs["sample_id"] = obs.get("Sample", obs.get("sample", "unknown"))
    obs["sample_label"] = obs["sample_id"].astype(str)
    obs["gsm_id"] = "unknown"
    obs["source_file"] = Path(count_path).name
    obs["source_accession"] = source_accession
    obs["dataset_id"] = dataset_id
    obs["data_status"] = "processed_SoupX_corrected"
    obs["processing_status"] = "SoupX_corrected"

    var = pd.DataFrame(index=pd.Index(gene_names, name=None).astype(str))
    var["gene_symbol"] = var.index
    var["gene_symbol_upper"] = var["gene_symbol"].str.upper()
    var["gene_id"] = var["gene_symbol"]
    var["ensembl_id"] = "unknown"
    var["feature_type"] = "unknown"

    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.obs_names = [
        f"{source_accession}_{x}" for x in adata.obs_names.astype(str)
    ]
    adata.obs["cell_id"] = adata.obs_names
    adata.var_names_make_unique()

    return adata


# ----------------------------
# 8. 実際にadata_fixedを作る
# ----------------------------
# 判定ロジック：
# small_no_header の列数が metadata rows と一致するなら headerなしとして読む。
# そうでなければ headerありとして読む。

if small_no_header.shape[1] == meta.shape[0]:
    print("\n>>> Using headerless whitespace gene x cell matrix")
    adata_fixed = build_adata_from_headerless_gene_by_cell_whitespace(
        count_path=count_path,
        meta=meta,
        dataset_id="GSE206330_sc_cortex_sod1_facs_glia_soupx",
        source_accession="GSE206330",
        chunksize=1000,
    )
else:
    print("\n>>> Using header whitespace gene x cell matrix")
    adata_fixed = build_adata_from_header_gene_by_cell_whitespace(
        count_path=count_path,
        meta=meta,
        dataset_id="GSE206330_sc_cortex_sod1_facs_glia_soupx",
        source_accession="GSE206330",
        chunksize=1000,
    )


# ----------------------------
# 9. 結果確認
# ----------------------------
adatas["GSE206330_fixed"] = adata_fixed

print("\n=== GSE206330 fixed ===")
nb.summarize_adata(adata_fixed, name="GSE206330_fixed")

display(adata_fixed)
display(adata_fixed.obs.head())
display(adata_fixed.var.head())

print("\nobs columns:")
print(list(adata_fixed.obs.columns))

print("\nvar columns:")
print(list(adata_fixed.var.columns))

print("\nX:")
print(type(adata_fixed.X), adata_fixed.X.shape, adata_fixed.X.dtype)
print("nnz:", adata_fixed.X.nnz if sp.issparse(adata_fixed.X) else np.count_nonzero(adata_fixed.X))
print("sum:", float(adata_fixed.X.sum()))

print("\nvalue counts for likely metadata columns:")
for col in ["Sample", "Condition", "Age", "cell_type", "sex",
            "meta_Sample", "meta_Condition", "meta_Age", "meta_cell_type", "meta_sex",
            "sample_id", "data_status", "processing_status"]:
    if col in adata_fixed.obs.columns:
        print(f"\n--- {col} ---")
        print(adata_fixed.obs[col].value_counts(dropna=False).head(30))


# ----------------------------
# 10. 必要なら一時保存
# ----------------------------
out_path = paths["interim"] / "GSE206330_sc_cortex_sod1_facs_glia_soupx.fixed_interim.h5ad"
print("\nwill save to:", out_path)

# 保存したくない場合は次の1行をコメントアウト
adata_fixed.write_h5ad(out_path)
print("saved:", out_path)

dataset keys: ['dataset_id', 'source_accession', 'parent_gse', 'loader_hint', 'file_type', 'data_status', 'output', 'matrix_file', 'metadata_files', 'files', 'metadata', 'notes']
dataset: {'dataset_id': 'GSE206330_sc_cortex_sod1_facs_glia_soupx', 'source_accession': 'GSE206330', 'parent_gse': 'GSE206330', 'loader_hint': 'processed_count_matrix_with_metadata', 'file_type': 'processed TXT + metadata CSV', 'data_status': 'processed_SoupX_corrected', 'output': 'GSE206330_sc_cortex_sod1_facs_glia_soupx.h5ad', 'matrix_file': 'GSE206330_processed_SoupX_corrected.txt.gz', 'metadata_files': [{'name': 'GSE206330_processed_SoupX_corrected_metadata.csv.gz', 'role': 'per_cell'}], 'files': [{'name': 'GSE206330_processed_SoupX_corrected.txt.gz', 'url': 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE206nnn/GSE206330/suppl/GSE206330_processed_SoupX_corrected.txt.gz', 'archive': False}, {'name': 'GSE206330_processed_SoupX_corrected_metadata.csv.gz', 'url': 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE206nnn/GSE206330/suppl/GSE206330_processed_SoupX_corrected_metadata.csv.gz', 'archive': False}, {'name': 'GSE206330_preprocessed_data.txt.gz', 'url': 'https://ftp.ncbi.nlm.nih.gov/geo/series/GSE206nnn/GSE206330/suppl/GSE206330_preprocessed_data.txt.gz', 'archive': False, 'optional': True}], 'metadata': {'species': 'Mus musculus', 'tissue': 'cerebral cortex', 'region': 'motor cortex-related cortical glia', 'assay': 'scRNA-seq', 'technology': '10x Genomics', 'enrichment': 'FACS enriched astrocytes/microglia/oligodendrocytes', 'disease_area': 'ALS', 'disease_model': 'SOD1G93A'}, 'notes': 'SoupX corrected processed data -> keep separate from raw counts.'}

raw_dir: /home/suzuki/Learn/SMA/v2/data/raw/GSE206330 exists= True
extracted_dir: /home/suzuki/Learn/SMA/v2/data/extracted/GSE206330 exists= False

raw files:
  GSE206330_preprocessed_data.txt.gz 100.6502332687378 MB
  GSE206330_processed_SoupX_corrected.txt.gz 460.9088068008423 MB
  GSE206330_processed_SoupX_corrected_metadata.csv.gz 1.2982511520385742 MB

extracted files:

count_path: /home/suzuki/Learn/SMA/v2/data/raw/GSE206330/GSE206330_processed_SoupX_corrected.txt.gz
meta_path : /home/suzuki/Learn/SMA/v2/data/raw/GSE206330/GSE206330_processed_SoupX_corrected_metadata.csv.gz

=== raw count file first 5 lines, repr ===
[line 1] len=582660
'"AAACCCAAGGGCTTCC.1M_CTRL" "AAACGAACAAATGAGT.1M_CTRL" "AAACGAAGTGGATACG.1M_CTRL" "AAAGAACAGTCTAACC.1M_CTRL" "AAAGAACGTCGGCTAC.1M_CTRL" "AAAGAACTCGCTACGG.1M_CTRL" "AAAGGGCAGTATGCAA.1M_CTRL" "AAAGGGCAGTTCCTGA.1M_CTRL" "AAAGTCCCACGGTCTG.1M_CTRL" "AACAAAGAGTCTTCCC.1M_CTRL" "AACAAAGTCAGCGCGT.1M_CTRL" "AACAAGAGTGTACAGG.1M_CTRL" "AACACACTCTCAACCC.1M_CTRL" "AACCAACGTATAATGG.1M_CTRL" "AACCAACTCCTAGCTC.1M_CTRL" "AACCCAAAGGCGTTGA.1M_CTRL" "AACGAAAGTCTAACTG.1M_CTRL" "AACGGGAAGGAAAGGT.1M_CTRL" "AACGGGACACAACGCC.1M_CTRL" "AACGGGACACCTCGTT.1M_CTRL" "AACGTCATCATCACTT.1M_CTRL" "AACTTCTCAGTCGTTA.1M_CTRL" "AAGAACACAGCACAAG.1M_CTRL" "AAGAACAGTGCAGTGA.1M_CTRL" "AAGATAGAGCGCCTCA.1M_CTRL" "AAGCATCGTGGCAGAT.1M_CTRL" "AAGCGAGCAAGGCAAC.1M_CTRL" "AAGCGAGTCCAAACCA.1M_CTRL" "AAGCGTTAGCAAGCCA.1M_CTRL" "AAGCGTTGTCCTGTCT.1M_CTRL" "AAGGTAATCCATAAGC.1M_CTRL" "AAGTACCCATACTTTC.1M_CTRL" "AAGTACCGTCACTCGG.1M_CTRL" "AAGTACCTCTTGAGCA.1M_CTRL" "AAGTCGTTCGGTAGGA.1M_CTRL" "AAGTGAATCACCGCTT.1M_CTRL" "AATAGAGAGTGGCAGT.1M_CTRL" "'

[line 2] len=43176
'"4933401J01Rik" 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 '

[line 3] len=43170
'"Gm26206" 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 '

[line 4] len=96493
'"Xkr4" 0 0 1.49844267293226 0 0 0 0 0 0.630135930066766 0 0.794880202968546 0 0 0 2.06400961582419 0 0.365156181999908 0 0.360757847491551 0 1.40286997019162 1.03395332231844 0 0.618761339836986 0.471517713718032 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.52666610541175 0 0 0 0 0 0 0 0 0.807987090233904 0 0 1.3228184774981 0 0.419131271258068 0.634729614989267 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1.80690354769124 0 0 0 0 0 0 0 0 0 0 0 1.1365072933727 0 0 0 1.27934646021545 0 0 0.64371855296412 1.4123814281855 0 0 0 0 0 0 0 0 0 1.24045570274312 0 0 0 0.594041712277215 0 0 0.855564995769564 0 0 0 0 0 0 0.847497452826031 0 0 0 0 0 0 0 0 0 0.586958664723667 0 0 0 0 0.375071190308656 0 0 0 0 0 0.619222812017031 0 0 0.50290397299057 0 0 0 0 1.15682066755083 0 0 1.3927404807392 0 0 0 0 0 0 0 0.394540983364075 0 0 0 0 0 0 2.06667464033202 0 0 0 0 0 0 1.34856015379582 0 0.912693730080801 0 0 0 0 0 2.19596893511908 0 0.38499251298466 0 1.58502831611581 0 0 0 0 0 0 0 0 0.731834433055054 0 0 0.4437017'

[line 5] len=43170
'"Gm18956" 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 '


=== metadata first 5 lines, repr ===
[line 1] len=197
'"","nCount_RNA","nFeature_RNA","Sample","Condition","Age","percent.mt","percent.rib","nCount_SCT","nFeature_SCT","seurat_clusters","cell_type","nCount_Y","nFeature_Y","nCount_X","nFeature_X","sex"\n'

[line 2] len=180
'"AAACCCAAGGGCTTCC-1M_CTRL",5070.14329005909,2006,"1M_CTRL","CTRL","1M",0.791865038460113,22.0357237540885,5171,2004,"1","Microglia",0.983752539745063,1,250.77533150599,64,"Female"\n'

[line 3] len=196
'"AAACGAACAAATGAGT-1M_CTRL",7314.61030935974,3210,"1M_CTRL","CTRL","1M",2.11044806066705,7.03620535014218,6389,3197,"17","Endothelial cells/Pericytes",6.95781807506145,3,246.115832444137,91,"Male"\n'

[line 4] len=173
'"AAACGAAGTGGATACG-1M_CTRL",20098.1120396051,4571,"1M_CTRL","CTRL","1M",2.42097483514742,3.24456346774506,6917,2878,"10","Oligodendrocytes",0,0,1645.89397418596,130,"Female"\n'

[line 5] len=176
'"AAAGAACAGTCTAACC-1M_CTRL",4071.95474221642,1735,"1M_CTRL","CTRL","1M",2.07406857305307,12.6194764878501,4656,1735,"1","Microglia",1.98229800810012,2,179.21960675448,51,"Male"\n'


--- try_read_head: tab + header + index sep='\t' header=infer index_col=0 ---
shape: (5, 0)
columns[:10]: []

Empty DataFrame
Columns: []

--- try_read_head: comma + header + index sep=',' header=infer index_col=0 ---
shape: (5, 0)
columns[:10]: []

Empty DataFrame
Columns: []

--- try_read_head: whitespace + header + index sep='\\s+' header=infer index_col=0 ---
shape: (5, 21580)
columns[:10]: ['"AAACCCAAGGGCTTCC.1M_CTRL"', '"AAACGAACAAATGAGT.1M_CTRL"', '"AAACGAAGTGGATACG.1M_CTRL"', '"AAAGAACAGTCTAACC.1M_CTRL"', '"AAAGAACGTCGGCTAC.1M_CTRL"', '"AAAGAACTCGCTACGG.1M_CTRL"', '"AAAGGGCAGTATGCAA.1M_CTRL"', '"AAAGGGCAGTTCCTGA.1M_CTRL"', '"AAAGTCCCACGGTCTG.1M_CTRL"', '"AACAAAGAGTCTTCCC.1M_CTRL"']
index[:5]: ['"4933401J01Rik"', '"Gm26206"', '"Xkr4"', '"Gm18956"', '"Gm37180"']

,"""AAACCCAAGGGCTTCC.1M_CTRL""","""AAACGAACAAATGAGT.1M_CTRL""","""AAACGAAGTGGATACG.1M_CTRL""","""AAAGAACAGTCTAACC.1M_CTRL""","""AAAGAACGTCGGCTAC.1M_CTRL""","""AAAGAACTCGCTACGG.1M_CTRL""","""AAAGGGCAGTATGCAA.1M_CTRL""","""AAAGGGCAGTTCCTGA.1M_CTRL""","""AAAGTCCCACGGTCTG.1M_CTRL""","""AACAAAGAGTCTTCCC.1M_CTRL"""
"""4933401J01Rik""",0,0,0.000000,0,0,0,0,0,0.000000,0
"""Gm26206""",0,0,0.000000,0,0,0,0,0,0.000000,0
"""Xkr4""",0,0,1.498443,0,0,0,0,0,0.630136,0
"""Gm18956""",0,0,0.000000,0,0,0,0,0,0.000000,0
"""Gm37180""",0,0,0.000000,0,0,0,0,0,0.000000,0

--- try_read_head: whitespace + NO header + index sep='\\s+' header=None index_col=0 ---
FAILED: ParserError Expected 21580 fields in line 2, saw 21581. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

--- try_read_head: metadata csv sep=',' header=infer index_col=0 ---
shape: (5, 16)
columns[:10]: ['nCount_RNA', 'nFeature_RNA', 'Sample', 'Condition', 'Age', 'percent.mt', 'percent.rib', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters']
index[:5]: ['AAACCCAAGGGCTTCC-1M_CTRL', 'AAACGAACAAATGAGT-1M_CTRL', 'AAACGAAGTGGATACG-1M_CTRL', 'AAAGAACAGTCTAACC-1M_CTRL', 'AAAGAACGTCGGCTAC-1M_CTRL']

,nCount_RNA,nFeature_RNA,Sample,Condition,Age,percent.mt,percent.rib,nCount_SCT,nFeature_SCT,seurat_clusters
AAACCCAAGGGCTTCC-1M_CTRL,5070.143290,2006,1M_CTRL,CTRL,1M,0.791865,22.035724,5171,2004,1
AAACGAACAAATGAGT-1M_CTRL,7314.610309,3210,1M_CTRL,CTRL,1M,2.110448,7.036205,6389,3197,17
AAACGAAGTGGATACG-1M_CTRL,20098.112040,4571,1M_CTRL,CTRL,1M,2.420975,3.244563,6917,2878,10
AAAGAACAGTCTAACC-1M_CTRL,4071.954742,1735,1M_CTRL,CTRL,1M,2.074069,12.619476,4656,1735,1
AAAGAACGTCGGCTAC-1M_CTRL,3142.309766,1480,1M_CTRL,CTRL,1M,1.658441,17.068558,4352,1480,1

=== metadata full ===
meta shape: (21580, 16)
meta index head: ['AAACCCAAGGGCTTCC-1M_CTRL', 'AAACGAACAAATGAGT-1M_CTRL', 'AAACGAAGTGGATACG-1M_CTRL', 'AAAGAACAGTCTAACC-1M_CTRL', 'AAAGAACGTCGGCTAC-1M_CTRL']
meta columns: ['nCount_RNA', 'nFeature_RNA', 'Sample', 'Condition', 'Age', 'percent.mt', 'percent.rib', 'nCount_SCT', 'nFeature_SCT', 'seurat_clusters', 'cell_type', 'nCount_Y', 'nFeature_Y', 'nCount_X', 'nFeature_X', 'sex']

,nCount_RNA,nFeature_RNA,Sample,Condition,Age,percent.mt,percent.rib,nCount_SCT,nFeature_SCT,seurat_clusters,cell_type,nCount_Y,nFeature_Y,nCount_X,nFeature_X,sex
AAACCCAAGGGCTTCC-1M_CTRL,5070.143290,2006,1M_CTRL,CTRL,1M,0.791865,22.035724,5171,2004,1,Microglia,0.983753,1,250.775332,64,Female
AAACGAACAAATGAGT-1M_CTRL,7314.610309,3210,1M_CTRL,CTRL,1M,2.110448,7.036205,6389,3197,17,Endothelial cells/Pericytes,6.957818,3,246.115832,91,Male
AAACGAAGTGGATACG-1M_CTRL,20098.112040,4571,1M_CTRL,CTRL,1M,2.420975,3.244563,6917,2878,10,Oligodendrocytes,0.000000,0,1645.893974,130,Female
AAAGAACAGTCTAACC-1M_CTRL,4071.954742,1735,1M_CTRL,CTRL,1M,2.074069,12.619476,4656,1735,1,Microglia,1.982298,2,179.219607,51,Male
AAAGAACGTCGGCTAC-1M_CTRL,3142.309766,1480,1M_CTRL,CTRL,1M,1.658441,17.068558,4352,1480,1,Microglia,0.000000,0,162.457076,37,Female

=== token diagnostics ===
line1 token count: 21580
line2 token count: 21581
line1 first 10 tokens: ['"AAACCCAAGGGCTTCC.1M_CTRL"', '"AAACGAACAAATGAGT.1M_CTRL"', '"AAACGAAGTGGATACG.1M_CTRL"', '"AAAGAACAGTCTAACC.1M_CTRL"', '"AAAGAACGTCGGCTAC.1M_CTRL"', '"AAAGAACTCGCTACGG.1M_CTRL"', '"AAAGGGCAGTATGCAA.1M_CTRL"', '"AAAGGGCAGTTCCTGA.1M_CTRL"', '"AAAGTCCCACGGTCTG.1M_CTRL"', '"AACAAAGAGTCTTCCC.1M_CTRL"']
line2 first 10 tokens: ['"4933401J01Rik"', '0', '0', '0', '0', '0', '0', '0', '0', '0']
metadata rows: 21580
headerless_gene_by_cell candidate: True
n numeric-like tokens in line1 after first token: 0

ParserError: Expected 21580 fields in line 2, saw 21581. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.

In [ ]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

Empty DataFrame
Columns: [cell_id_original, sample_id, sample_label, gsm_id, source_file, source_accession, dataset_id, meta_nCount_RNA, meta_nFeature_RNA, meta_Sample, meta_Condition, meta_Age, meta_percent.mt, meta_percent.rib, meta_nCount_SCT, meta_nFeature_SCT, meta_seurat_clusters, meta_cell_type, meta_nCount_Y, meta_nFeature_Y, meta_nCount_X, meta_nFeature_X, meta_sex]
Index: []

[0 rows x 23 columns]

                                                                                          gene_symbol  \
4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.630135930...  Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.63013593...
Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

                                                                                    gene_symbol_upper  \
4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  4933401J01RIK 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  GM26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.630135930...  XKR4 0 0 1.49844267293226 0 0 0 0 0 0.63013593...
Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  GM18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  GM37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

                                                                                              gene_id  \
4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.630135930...  Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.63013593...
Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...
Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...  Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

                                                   ensembl_id feature_type
4933401J01Rik 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...    unknown      unknown
Gm26206 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...    unknown      unknown
Xkr4 0 0 1.49844267293226 0 0 0 0 0 0.630135930...    unknown      unknown
Gm18956 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...    unknown      unknown
Gm37180 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0...    unknown      unknown

--- cell_id_original (0 unique) ---
Series([], )

--- sample_id (0 unique) ---
Series([], )

--- sample_label (0 unique) ---
Series([], )

--- gsm_id (0 unique) ---
Series([], )

--- source_file (0 unique) ---
Series([], )

--- source_accession (0 unique) ---
Series([], )

--- dataset_id (0 unique) ---
Series([], )

--- meta_nCount_RNA (0 unique) ---
Series([], )

--- meta_nFeature_RNA (0 unique) ---
Series([], )

--- meta_Sample (0 unique) ---
Series([], )

--- meta_Condition (0 unique) ---
Series([], )

--- meta_Age (0 unique) ---
Series([], )

--- meta_percent.mt (0 unique) ---
Series([], )

--- meta_percent.rib (0 unique) ---
Series([], )

--- meta_nCount_SCT (0 unique) ---
Series([], )

--- meta_nFeature_SCT (0 unique) ---
Series([], )

--- meta_seurat_clusters (0 unique) ---
Series([], )

--- meta_cell_type (0 unique) ---
Series([], )

--- meta_nCount_Y (0 unique) ---
Series([], )

--- meta_nFeature_Y (0 unique) ---
Series([], )

--- meta_nCount_X (0 unique) ---
Series([], )

--- meta_nFeature_X (0 unique) ---
Series([], )

--- meta_sex (0 unique) ---
Series([], )

## GSE178693

ネスト TAR（Drop-seq）

In [19]:
ds = mf.get_dataset(man, "GSE178693")
adata = io_dense.load_nested_tar_dropseq(ds, paths)
adatas["GSE178693"] = adata
nb.summarize_adata(adata, name="GSE178693")
adata

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

=== GSE178693 ===
15472 cells x 23903 genes | X sparse=True dtype=float32 min=0.0 max=16100.0 sum=12286897.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

AnnData object with n_obs × n_vars = 15472 × 23903
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [ ]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

## GSE295514

RDS → R 中間ファイル（先に R ノートブックを実行）

In [3]:
ds = mf.get_dataset(man, "GSE295514")
adata = io_dense.read_from_r_intermediate(paths['intermediate_from_r'] / 'GSE295514', ds)
adatas["GSE295514"] = adata
nb.summarize_adata(adata, name="GSE295514")
adata

=== GSE295514 ===
123401 cells x 24134 genes | X sparse=True dtype=float32 min=0.0 max=37299.0 sum=909639936.0
obs columns (10): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'meta_orig.ident', 'meta_nCount_RNA', 'meta_nFeature_RNA']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

AnnData object with n_obs × n_vars = 123401 × 24134
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'meta_orig.ident', 'meta_nCount_RNA', 'meta_nFeature_RNA'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [4]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,meta_orig.ident,meta_nCount_RNA,meta_nFeature_RNA
GEX_S1_ALS-FC1_AAACCCAAGAAACCCG-1,GEX_S1_ALS-FC1_AAACCCAAGAAACCCG-1,unknown,unknown,unknown,GSE295514_ALS_mouse_brain.rds,GSE295514,GSE295514_sc_brain_rnls8_tdp43_rds,GEX_S1_ALS-FC1,12547,4470
GEX_S1_ALS-FC1_AAACCCAAGCGTGCTC-1,GEX_S1_ALS-FC1_AAACCCAAGCGTGCTC-1,unknown,unknown,unknown,GSE295514_ALS_mouse_brain.rds,GSE295514,GSE295514_sc_brain_rnls8_tdp43_rds,GEX_S1_ALS-FC1,4287,1805
GEX_S1_ALS-FC1_AAACCCAAGGAGTCTG-1,GEX_S1_ALS-FC1_AAACCCAAGGAGTCTG-1,unknown,unknown,unknown,GSE295514_ALS_mouse_brain.rds,GSE295514,GSE295514_sc_brain_rnls8_tdp43_rds,GEX_S1_ALS-FC1,3255,1598
GEX_S1_ALS-FC1_AAACCCAAGGTAAGGA-1,GEX_S1_ALS-FC1_AAACCCAAGGTAAGGA-1,unknown,unknown,unknown,GSE295514_ALS_mouse_brain.rds,GSE295514,GSE295514_sc_brain_rnls8_tdp43_rds,GEX_S1_ALS-FC1,4995,1617
GEX_S1_ALS-FC1_AAACCCAAGTGGCCTC-1,GEX_S1_ALS-FC1_AAACCCAAGTGGCCTC-1,unknown,unknown,unknown,GSE295514_ALS_mouse_brain.rds,GSE295514,GSE295514_sc_brain_rnls8_tdp43_rds,GEX_S1_ALS-FC1,9165,3142

        gene_symbol gene_symbol_upper  gene_id ensembl_id feature_type
Xkr4           Xkr4              XKR4     Xkr4    unknown      unknown
Gm19938     Gm19938           GM19938  Gm19938    unknown      unknown
Rp1             Rp1               RP1      Rp1    unknown      unknown
Sox17         Sox17             SOX17    Sox17    unknown      unknown
Gm37587     Gm37587           GM37587  Gm37587    unknown      unknown

--- cell_id_original (123401 unique) ---
cell_id_original
GEX_S8_ALS-M2_TTTGTTGTCTGTACAG-1     1
GEX_S1_ALS-FC1_AAACCCAAGAAACCCG-1    1
GEX_S1_ALS-FC1_AAACCCAAGCGTGCTC-1    1
GEX_S1_ALS-FC1_AAACCCAAGGAGTCTG-1    1
GEX_S1_ALS-FC1_AAACCCAAGGTAAGGA-1    1
GEX_S1_ALS-FC1_AAACCCAAGTGGCCTC-1    1
GEX_S1_ALS-FC1_AAACCCACACAACGTT-1    1
GEX_S1_ALS-FC1_AAACCCACACCAGTAT-1    1
GEX_S1_ALS-FC1_AAACCCACACTTGGGC-1    1
GEX_S8_ALS-M2_TTTGGAGTCCCATTTA-1     1
GEX_S8_ALS-M2_TTTGGAGTCGCATAGT-1     1
GEX_S8_ALS-M2_TTTGGAGTCGCTGATA-1     1
GEX_S8_ALS-M2_TTTGGAGTCGGTTCAA-1     1
GEX_S8_ALS-M2_TTTGGTTAGCCAAGTG-1     1
GEX_S8_ALS-M2_TTTGGTTCATAGTCAC-1     1
GEX_S8_ALS-M2_TTTGGTTCATGGAAGC-1     1
GEX_S8_ALS-M2_TTTGGTTGTACAATAG-1     1
GEX_S8_ALS-M2_TTTGGAGCATCGCTGG-1     1
GEX_S8_ALS-M2_TTTGGAGCATTGAAGA-1     1
GEX_S8_ALS-M2_TTTGGAGGTCGGAACA-1     1
GEX_S8_ALS-M2_TTTGGAGGTCGTATTG-1     1
GEX_S8_ALS-M2_TTTGGAGGTCTAGGTT-1     1
GEX_S8_ALS-M2_TTTGGAGGTCTTACTT-1     1
GEX_S8_ALS-M2_TTTGGAGGTTACACTG-1     1
GEX_S8_ALS-M2_TTTGGAGGTTCAAACC-1     1
GEX_S8_ALS-M2_TTTGGAGAGAAGGGAT-1     1
GEX_S8_ALS-M2_TTTGGAGAGAGAGCGG-1     1
GEX_S8_ALS-M2_TTTGGAGAGCGGACAT-1     1
GEX_S8_ALS-M2_TTTGGAGCAATCTCGA-1     1
GEX_S8_ALS-M2_TTTGGAGCAATTTCCT-1     1

--- sample_id (1 unique) ---
sample_id
unknown    123401

--- sample_label (1 unique) ---
sample_label
unknown    123401

--- gsm_id (1 unique) ---
gsm_id
unknown    123401

--- source_file (1 unique) ---
source_file
GSE295514_ALS_mouse_brain.rds    123401

--- source_accession (1 unique) ---
source_accession
GSE295514    123401

--- dataset_id (1 unique) ---
dataset_id
GSE295514_sc_brain_rnls8_tdp43_rds    123401

--- meta_orig.ident (8 unique) ---
meta_orig.ident
GEX_S4_ALS-M1     19641
GEX_S8_ALS-M2     17023
GEX_S2_ALS-MC1    16867
GEX_S3_ALS-F1     16201
GEX_S1_ALS-FC1    15119
GEX_S5_ALS-FC2    14779
GEX_S6_ALS-MC2    12200
GEX_S7_ALS-F2     11571

## GSE208629

10x MTX/サンプル（SMA）

In [20]:
ds = mf.get_dataset(man, "GSE208629")
adata = io_10x.load_10x_mtx_per_sample(ds, paths)
adatas["GSE208629"] = adata
nb.summarize_adata(adata, name="GSE208629")
adata

=== GSE208629 ===
52340 cells x 32285 genes | X sparse=True dtype=float32 min=0.0 max=12270.0 sum=183766160.0
obs columns (8): ['cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id']
var columns (5): ['gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type']
layers=[] obsm=[] uns=[]

/home/suzuki/.conda/envs/scdiffusion_jupyter/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 52340 × 32285
    obs: 'cell_id_original', 'sample_id', 'sample_label', 'gsm_id', 'source_file', 'source_accession', 'dataset_id', 'cell_id'
    var: 'gene_symbol', 'gene_symbol_upper', 'gene_id', 'ensembl_id', 'feature_type'

In [21]:
# その場で確認
display(adata.obs.head())
display(adata.var.head())
_ = nb.show_obs_value_counts(adata, max_unique=30)

,cell_id_original,sample_id,sample_label,gsm_id,source_file,source_accession,dataset_id,cell_id
GSE208629_SMA_AAACCCAAGAGGTTTA-1,AAACCCAAGAGGTTTA-1,SMA,SMA,GSM6355861,GSM6355861_SMA_matrix.mtx.gz,GSE208629,GSE208629_sc_spinalcord_sma,GSE208629_SMA_AAACCCAAGAGGTTTA-1
GSE208629_SMA_AAACCCAAGCTGCCAC-1,AAACCCAAGCTGCCAC-1,SMA,SMA,GSM6355861,GSM6355861_SMA_matrix.mtx.gz,GSE208629,GSE208629_sc_spinalcord_sma,GSE208629_SMA_AAACCCAAGCTGCCAC-1
GSE208629_SMA_AAACCCAAGGACGCAT-1,AAACCCAAGGACGCAT-1,SMA,SMA,GSM6355861,GSM6355861_SMA_matrix.mtx.gz,GSE208629,GSE208629_sc_spinalcord_sma,GSE208629_SMA_AAACCCAAGGACGCAT-1
GSE208629_SMA_AAACCCAAGGCTCTCG-1,AAACCCAAGGCTCTCG-1,SMA,SMA,GSM6355861,GSM6355861_SMA_matrix.mtx.gz,GSE208629,GSE208629_sc_spinalcord_sma,GSE208629_SMA_AAACCCAAGGCTCTCG-1
GSE208629_SMA_AAACCCAAGGTACCTT-1,AAACCCAAGGTACCTT-1,SMA,SMA,GSM6355861,GSM6355861_SMA_matrix.mtx.gz,GSE208629,GSE208629_sc_spinalcord_sma,GSE208629_SMA_AAACCCAAGGTACCTT-1

,gene_symbol,gene_symbol_upper,gene_id,ensembl_id,feature_type
Xkr4,Xkr4,XKR4,ENSMUSG00000051951,ENSMUSG00000051951,Gene Expression
Gm1992,Gm1992,GM1992,ENSMUSG00000089699,ENSMUSG00000089699,Gene Expression
Gm19938,Gm19938,GM19938,ENSMUSG00000102331,ENSMUSG00000102331,Gene Expression
Gm37381,Gm37381,GM37381,ENSMUSG00000102343,ENSMUSG00000102343,Gene Expression
Rp1,Rp1,RP1,ENSMUSG00000025900,ENSMUSG00000025900,Gene Expression

--- cell_id_original (44177 unique) ---
cell_id_original
TACGTCCCACTCTAGA-1    2
CCAATTTGTCACGCTG-1    2
TACGTCCCACTACAGT-1    2
CCAATTTGTCTGTTAG-1    2
TACGTCCCACAGTCAT-1    2
CCAATTTTCCTACTGC-1    2
CCAATTTTCGCCACTT-1    2
TACGTCCAGGATGTTA-1    2
TACGTCCAGATTACCC-1    2
ATCAGGTAGATGAAGG-1    2
TACGGTATCGTTCTCG-1    2
TACGGTATCGAATGCT-1    2
TACGGTAGTGAGTAGC-1    2
CCACAAACAGTTTGGT-1    2
CCACAAAGTAAGTTGA-1    2
CCACAAAGTCGTTGCG-1    2
CCACAAAGTGATATAG-1    2
TACGGTACATGGAAGC-1    2
TACGGTACACACCTAA-1    2
CCACAAAAGCCTCTGG-1    2
CCAAGCGTCGCTCCTA-1    2
TACTGCCTCACACCGG-1    2
CCAATGAAGAGGTGCT-1    2
TACTGCCGTTCCGCTT-1    2
TACTGCCGTGCATCTA-1    2
TACTGCCGTGACTATC-1    2
TACTGCCGTCTTTCAT-1    2
TACTGCCGTCGCGTTG-1    2
CCAATGACATCAGTCA-1    2
TACGTCCGTAATCAAG-1    2

--- sample_id (2 unique) ---
sample_id
SMA    26921
Con    25419

--- sample_label (2 unique) ---
sample_label
SMA    26921
Con    25419

--- gsm_id (2 unique) ---
gsm_id
GSM6355861    26921
GSM6355862    25419

--- source_file (2 unique) ---
source_file
GSM6355861_SMA_matrix.mtx.gz    26921
GSM6355862_Con_matrix.mtx.gz    25419

--- source_accession (1 unique) ---
source_accession
GSE208629    52340

--- dataset_id (1 unique) ---
dataset_id
GSE208629_sc_spinalcord_sma    52340

--- cell_id (52340 unique) ---
cell_id
GSE208629_Con_TTTGTTGTCTTTCAGT-1    1
GSE208629_SMA_AAACCCAAGAGGTTTA-1    1
GSE208629_SMA_AAACCCAAGCTGCCAC-1    1
GSE208629_SMA_AAACCCAAGGACGCAT-1    1
GSE208629_SMA_AAACCCAAGGCTCTCG-1    1
GSE208629_SMA_AAACCCAAGGTACCTT-1    1
GSE208629_SMA_AAACCCAAGTCAAGCG-1    1
GSE208629_SMA_AAACCCAAGTCATCGT-1    1
GSE208629_SMA_AAACCCAAGTCTGGAG-1    1
GSE208629_SMA_AAACCCAAGTGAGGCT-1    1
GSE208629_SMA_AAACCCAAGTGCAAAT-1    1
GSE208629_SMA_AAACCCACAAATGAGT-1    1
GSE208629_SMA_AAACCCACAACGTTAC-1    1
GSE208629_SMA_AAACCCACAATGTCTG-1    1
GSE208629_SMA_AAACCCACACAAATGA-1    1
GSE208629_SMA_AAACCCACACATGAAA-1    1
GSE208629_SMA_AAACCCACACCTAAAC-1    1
GSE208629_SMA_AAACCCACACTCGATA-1    1
GSE208629_SMA_AAACCCACAGAACGCA-1    1
GSE208629_SMA_AAACCCACAGGACAGT-1    1
GSE208629_Con_TTTGGTTCAAAGCAAT-1    1
GSE208629_Con_TTTGGTTCAGAGTTCT-1    1
GSE208629_Con_TTTGGTTCAGTTACCA-1    1
GSE208629_Con_TTTGGTTCATCAGTGT-1    1
GSE208629_Con_TTTGGTTCATCCGAGC-1    1
GSE208629_Con_TTTGGTTCATCGAAGG-1    1
GSE208629_Con_TTTGGTTCATGCCATA-1    1
GSE208629_Con_TTTGGTTCATTGTACG-1    1
GSE208629_Con_TTTGGAGTCTGTTGGA-1    1
GSE208629_Con_TTTGGAGTCTTACCAT-1    1

## interim_h5ad として保存（02 で読み直す用）

In [ ]:
for acc, adata in adatas.items():
    ds = mf.get_dataset(man, acc)
    au.save_h5ad(adata, paths['interim'] / (ds['dataset_id'] + '.h5ad'), overwrite=True)

次: **02_curate_each_gse_and_save_h5ad.ipynb**